// 003.前端代码（前端工程师）/frontend-react/src/pages/Settings.tsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { usePageTitle, usePageBack } from '../components/PageTitleContext'
import { useAuth } from '../auth/AuthContext'
import { LANGS, useLanguage, type Lang } from '../i18n/LanguageContext'
import { useTheme, type ThemeMode } from '../theme/ThemeContext'
import { useVersion } from '../version/VersionContext'
import { exportAll, exportByCategory, exportMonthly } from '../lib/export'

const THEME_OPTIONS: { mode: ThemeMode; labelKey: string }[] = [
  { mode: 'system', labelKey: 'settings.prefs.theme.system' },
  { mode: 'light', labelKey: 'settings.prefs.theme.light' },
  { mode: 'dark', labelKey: 'settings.prefs.theme.dark' },
]

export function Settings() {
  usePageTitle('设置')
  usePageBack(null)

  const { user, logout } = useAuth()
  const navigate = useNavigate()
  const { mode: themeMode, setMode: setThemeMode } = useTheme()
  const { lang, setLang, t } = useLanguage()
  const { version, state: versionState } = useVersion()
  const [exporting, setExporting] = useState<null | 'monthly' | 'category' | 'all'>(null)
  const [exportErr, setExportErr] = useState<string | null>(null)

  function handleLogout() {
    logout()
    navigate('/login')
  }

  async function runExport(kind: 'monthly' | 'category' | 'all'): Promise<void> {
    setExportErr(null)
    setExporting(kind)
    try {
      if (kind === 'monthly') await exportMonthly()
      else if (kind === 'category') await exportByCategory()
      else await exportAll()
    } catch (err) {
      console.error('[export] failed', err)
      setExportErr(err instanceof Error ? err.message : '导出失败')
    } finally {
      setExporting(null)
    }
  }

  const genderText =
    user?.gender === 'male' ? t('settings.userCard.gender.male') :
    user?.gender === 'female' ? t('settings.userCard.gender.female') :
    user?.gender === 'other' ? t('settings.userCard.gender.other') :
    t('settings.userCard.gender.none')
  const ageText = user?.age != null ? String(user.age) : t('settings.userCard.age.none')

  return (
    <div className="space-y-6">
      {/* 标题 */}
      <h2 className="font-headline-md text-headline-md text-on-surface">
        {t('settings.heading')}
      </h2>

      {/* 顶部：用户卡片 + 系统偏好 */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* 用户卡片 — 卡片骨架始终保留；有 user 时显示完整资料；me() 失败时只显示默认头像 + 账号「—」(由 AuthContext 触发全局 toast 提示) */}
        <div className="bento-item bg-bg-card lg:col-span-4 flex flex-col items-center text-center p-8">
          {/* 头像 + 设置·轻账 弧形文字 */}
          <div className="relative w-32 h-32 mb-4">
            <svg viewBox="0 0 120 120" className="absolute inset-0 w-full h-full">
              <defs>
                <path
                  id="circlePath"
                  d="M 60,60 m -48,0 a 48,48 0 1,1 96,0 a 48,48 0 1,1 -96,0"
                />
              </defs>
              <text
                fill="#414750"
                fontSize="9"
                letterSpacing="3"
                style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
              >
                <textPath href="#circlePath" startOffset="0%">
                  设置 · 轻账 ·
                </textPath>
              </text>
            </svg>
            <div className="absolute inset-3 rounded-full bg-gradient-to-br from-primary-light to-primary flex items-center justify-center overflow-hidden">
              {user?.avatar ? (
                <img
                  src={user.avatar}
                  alt="头像"
                  className="w-full h-full object-cover rounded-full"
                />
              ) : (
                <span
                  className="material-symbols-outlined text-white"
                  style={{ fontSize: '56px', fontVariationSettings: "'FILL' 0", fontWeight: 300 }}
                >
                  person
                </span>
              )}
            </div>
          </div>

          {user ? (
            <>
              <h3 className="font-headline-md text-headline-md text-text-primary mb-1">
                {user.displayName || user.username}
              </h3>
              <p className="font-body-md text-body-md text-on-surface-variant mb-1">
                {t('settings.userCard.accountLabel')}：{user.username}
              </p>
              <p className="font-body-md text-body-md text-on-surface-variant mb-1">
                {t('settings.userCard.freeVersion')}
              </p>
              <p className="font-body-md text-body-md text-on-surface-variant mb-1">
                {t('settings.userCard.genderLabel')}：{genderText}
              </p>
              <p className="font-body-md text-body-md text-on-surface-variant mb-6">
                {t('settings.userCard.ageLabel')}：{ageText}
              </p>

              <Link
                to="/profile/edit"
                className="w-full block text-center py-2.5 px-4 border border-outline text-on-surface font-body-md text-body-md rounded-lg hover:bg-surface-container-low transition-colors"
              >
                {t('settings.userCard.editProfile')}
              </Link>
            </>
          ) : (
            <p className="font-body-md text-body-md text-on-surface-variant">
              {t('settings.userCard.accountLabel')}：—
            </p>
          )}
        </div>

        {/* 系统偏好 */}
        <div className="bento-item bg-bg-card lg:col-span-8 p-8">
          <div className="flex items-center gap-3 mb-8">
            <span
              className="w-9 h-9 rounded-full flex items-center justify-center bg-primary-light text-primary"
            >
              <span
                className="material-symbols-outlined"
                style={{ fontSize: '20px', fontVariationSettings: "'FILL' 1" }}
              >
                tune
              </span>
            </span>
            <h3 className="font-headline-md text-headline-md text-text-primary">
              {t('settings.prefs.title')}
            </h3>
          </div>

          {/* 深色模式 — 3 档 segmented */}
          <div className="flex items-center justify-between pb-6">
            <div>
              <p className="font-headline-md text-headline-md text-text-primary mb-1">
                {t('settings.prefs.theme.label')}
              </p>
              <p className="font-body-md text-body-md text-on-surface-variant">
                {t('settings.prefs.theme.desc')}
              </p>
            </div>
            <div
              role="radiogroup"
              aria-label={t('settings.prefs.theme.label')}
              className="inline-flex p-1 rounded-lg bg-surface-container-low border border-divider"
            >
              {THEME_OPTIONS.map((opt) => {
                const active = themeMode === opt.mode
                return (
                  <button
                    key={opt.mode}
                    type="button"
                    role="radio"
                    aria-checked={active}
                    onClick={() => setThemeMode(opt.mode)}
                    className={
                      'px-3 py-1.5 text-sm rounded-md transition-colors ' +
                      (active
                        ? 'bg-bg-card text-text-primary shadow-sm'
                        : 'text-on-surface-variant hover:text-text-primary')
                    }
                  >
                    {t(opt.labelKey)}
                  </button>
                )
              })}
            </div>
          </div>

          <div className="border-t border-divider" />

          {/* 语言 */}
          <div className="flex items-center justify-between pt-6">
            <div>
              <p className="font-headline-md text-headline-md text-text-primary mb-1">
                {t('settings.prefs.lang.label')}
              </p>
              <p className="font-body-md text-body-md text-on-surface-variant">
                {t('settings.prefs.lang.desc')}
              </p>
            </div>
            <div className="relative">
              <select
                value={lang}
                onChange={(e) => setLang(e.target.value as Lang)}
                className="appearance-none bg-surface-container-low border border-outline rounded-lg pl-5 pr-10 py-2 font-body-md text-body-md text-text-primary hover:border-primary focus:border-primary focus:ring-1 focus:ring-primary transition-colors cursor-pointer"
              >
                {LANGS.map((l) => (
                  <option key={l.code} value={l.code}>
                    {l.label}
                  </option>
                ))}
              </select>
              <span
                className="material-symbols-outlined absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-on-surface-variant"
                style={{ fontSize: '20px' }}
              >
                expand_more
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* 中部：数据管理 */}
      <div className="bento-item bg-bg-card p-8">
        <div className="flex items-center gap-3 mb-8">
          <span
            className="w-9 h-9 rounded-full flex items-center justify-center bg-primary-light text-primary"
          >
            <span
              className="material-symbols-outlined"
              style={{ fontSize: '20px', fontVariationSettings: "'FILL' 1" }}
            >
              database
            </span>
          </span>
          <h3 className="font-headline-md text-headline-md text-text-primary">数据管理</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          {/* 导出本月报表 */}
          <button
            type="button"
            disabled={exporting !== null}
            onClick={() => runExport('monthly')}
            className="flex flex-col items-center justify-center gap-3 py-10 px-4 border border-divider rounded-xl bg-surface-container-lowest hover:border-primary hover:bg-primary-light/40 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:border-divider disabled:hover:bg-surface-container-lowest"
          >
            <span
              className="material-symbols-outlined text-on-surface-variant"
              style={{ fontSize: '36px', fontVariationSettings: "'FILL' 0", fontWeight: 300 }}
            >
              {exporting === 'monthly' ? 'progress_activity' : 'calendar_month'}
            </span>
            <span className="font-body-md text-body-md text-text-primary">
              {exporting === 'monthly' ? '导出中…' : '导出本月报表'}
            </span>
          </button>

          {/* 按分类导出 */}
          <button
            type="button"
            disabled={exporting !== null}
            onClick={() => runExport('category')}
            className="flex flex-col items-center justify-center gap-3 py-10 px-4 border border-divider rounded-xl bg-surface-container-lowest hover:border-primary hover:bg-primary-light/40 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:border-divider disabled:hover:bg-surface-container-lowest"
          >
            <span
              className="material-symbols-outlined text-on-surface-variant"
              style={{ fontSize: '36px', fontVariationSettings: "'FILL' 0", fontWeight: 300 }}
            >
              {exporting === 'category' ? 'progress_activity' : 'category'}
            </span>
            <span className="font-body-md text-body-md text-text-primary">
              {exporting === 'category' ? '导出中…' : '按分类导出'}
            </span>
          </button>

          {/* 导出全部数据 */}
          <button
            type="button"
            disabled={exporting !== null}
            onClick={() => runExport('all')}
            className="flex flex-col items-center justify-center gap-3 py-10 px-4 border border-divider rounded-xl bg-surface-container-lowest hover:border-primary hover:bg-primary-light/40 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:border-divider disabled:hover:bg-surface-container-lowest"
          >
            <span
              className="material-symbols-outlined text-on-surface-variant"
              style={{ fontSize: '36px', fontVariationSettings: "'FILL' 0", fontWeight: 300 }}
            >
              {exporting === 'all' ? 'progress_activity' : 'check_circle'}
            </span>
            <span className="font-body-md text-body-md text-text-primary">
              {exporting === 'all' ? '导出中…' : '导出全部数据'}
            </span>
          </button>
        </div>

        <p className="text-center font-body-md text-body-md text-on-surface-variant">
          {exportErr
            ? `导出失败:${exportErr}`
            : '所有数据将以 Excel (.xlsx) 格式导出至您的设备。'}
        </p>
      </div>

      {/* 底部：关于轻账 + 账号安全 */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* 关于轻账 */}
        <div className="bento-item bg-bg-card lg:col-span-7 p-8">
          <div className="flex items-center gap-3 mb-8">
            <span
              className="material-symbols-outlined text-primary"
              style={{ fontSize: '22px', fontVariationSettings: "'FILL' 1" }}
            >
              info
            </span>
            <h3 className="font-headline-md text-headline-md text-text-primary">关于轻账</h3>
          </div>

          <div className="flex items-start gap-4 mb-8">
            <div className="w-14 h-16 rounded-lg bg-primary-light flex items-center justify-center flex-shrink-0">
              <span className="font-display-lg text-display-lg text-primary font-bold">
                Q
              </span>
            </div>
            <div>
              <p
                className="font-headline-md text-headline-md text-text-primary font-semibold mb-1"
                aria-busy={versionState === 'loading'}
              >
                {versionState === 'loading'
                  ? 'QingZhang v…'
                  : versionState === 'error'
                    ? 'QingZhang v—'
                    : `QingZhang v${version}`}
              </p>
              <p className="font-body-md text-body-md text-on-surface-variant">
                {versionState === 'ok'
                  ? '当前版本'
                  : versionState === 'error'
                    ? '暂不可用,请稍后重试'
                    : '正在获取版本号…'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-6 pt-4 border-t border-divider">
            <a
              href="#"
              className="font-body-md text-body-md text-primary hover:underline"
            >
              服务条款
            </a>
            <a
              href="#"
              className="font-body-md text-body-md text-primary hover:underline"
            >
              隐私政策
            </a>
          </div>
        </div>

        {/* 账号安全 */}
        <div className="bento-item bg-bg-card lg:col-span-5 p-8 flex flex-col">
          <div className="flex items-center gap-3 mb-6">
            <span
              className="material-symbols-outlined"
              style={{ fontSize: '22px', color: '#ba1a1a', fontVariationSettings: "'FILL' 1" }}
            >
              shield
            </span>
            <h3 className="font-headline-md text-headline-md text-text-primary">账号安全</h3>
          </div>

          <p className="font-body-md text-body-md text-on-surface-variant mb-8 leading-relaxed">
            退出登录后，需要重新输入密码或使用生物识别认证才能再次访问您的账单数据。
          </p>

          <div className="mt-auto flex justify-end">
            <button
              type="button"
              onClick={handleLogout}
              className="inline-flex items-center gap-2 px-5 py-2.5 border-2 border-error text-error font-body-md text-body-md rounded-lg hover:bg-error hover:text-white transition-colors"
            >
              <span
                className="material-symbols-outlined"
                style={{ fontSize: '18px', fontVariationSettings: "'FILL' 1" }}
              >
                logout
              </span>
              退出登录
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// 007.跨端APP应用（移动端开发工程师）/uniapp-conversion/src/pages/settings/index.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useThemeStore } from '@/stores/theme'
import { useLanguage, LANGS } from '@/i18n/useLanguage'
import { useToastStore } from '@/stores/toast'
import { getSystemVersion } from '@/api/version'
import { listCategories, createCategory, updateCategory, deleteCategory } from '@/api/categories'
import type { Category, CategoryType } from '@/api/categories'
import { t } from '@/i18n/dict'

const auth = useAuthStore()
const theme = useThemeStore()
const { lang, setLang } = useLanguage()
const toast = useToastStore()

// ── version ────────────────────────────────────────────────────────────────
const version = ref('')
const versionState = ref<'loading' | 'ok' | 'error'>('loading')
onMounted(async () => {
  try {
    const r = await getSystemVersion()
    version.value = r.version
    versionState.value = 'ok'
  } catch {
    versionState.value = 'error'
  }
})

// ── helpers ────────────────────────────────────────────────────────────────
const genderText = computed(() => {
  const g = auth.user?.gender
  if (g === 'male') return t(lang, 'settings.userCard.gender.male')
  if (g === 'female') return t(lang, 'settings.userCard.gender.female')
  if (g === 'other') return t(lang, 'settings.userCard.gender.other')
  return t(lang, 'settings.userCard.gender.none')
})
const ageText = computed(() =>
  auth.user?.age != null ? String(auth.user.age) : t(lang, 'settings.userCard.age.none')
)

function navigateToEdit() {
  uni.navigateTo({ url: '/pages/profile/edit' })
}

async function handleLogout() {
  await auth.logout()
  uni.reLaunch({ url: '/pages/login/index' })
}

// ── theme ──────────────────────────────────────────────────────────────────
const themeOptions = [
  { mode: 'system' as const, labelKey: 'settings.prefs.theme.system' },
  { mode: 'light' as const, labelKey: 'settings.prefs.theme.light' },
  { mode: 'dark' as const, labelKey: 'settings.prefs.theme.dark' },
]

// ── language picker ────────────────────────────────────────────────────────
const langIndex = computed(() => LANGS.findIndex(l => l.code === lang))
function onLangChange(e: any) {
  const idx = Number(e.detail.value)
  setLang(LANGS[idx].code)
}

// ── categories ────────────────────────────────────────────────────────────
const expenseCats = ref<Category[]>([])
const incomeCats = ref<Category[]>([])
const catTab = ref<CategoryType>('expense')
const showNew = ref(false)
const newName = ref('')
const newIcon = ref('🏷️')
const newColor = ref('#A0AEC0')
const busy = ref(false)
const editing = ref<Category | null>(null)
const editName = ref('')
const editColor = ref('')

const catItems = computed(() => catTab.value === 'expense' ? expenseCats : incomeCats)

async function loadCategories() {
  try {
    const [exp, inc] = await Promise.all([listCategories('expense'), listCategories('income')])
    expenseCats.value = exp
    incomeCats.value = inc
  } catch {
    toast.show(t(lang, 'common.error'))
  }
}
onMounted(loadCategories)

async function handleCreate() {
  if (!newName.value.trim()) return
  busy.value = true
  try {
    await createCategory({ type: catTab.value, name: newName.value.trim(), icon: newIcon.value || '🏷️', color: newColor.value })
    showNew.value = false
    newName.value = ''
    newIcon.value = '🏷️'
    newColor.value = '#A0AEC0'
    toast.show(t(lang, 'settings.categories.create.success'))
    await loadCategories()
  } catch (err: any) {
    toast.show(t(lang, 'settings.categories.create.failPrefix') + (err?.message ?? ''))
  } finally {
    busy.value = false
  }
}

function openEdit(c: Category) {
  editing.value = c
  editName.value = c.name
  editColor.value = c.color
}

async function handleSaveEdit() {
  if (!editing.value) return
  busy.value = true
  try {
    await updateCategory(editing.value.id, { name: editName.value.trim() || undefined, color: editColor.value || undefined })
    editing.value = null
    toast.show(t(lang, 'settings.categories.edit.success'))
    await loadCategories()
  } catch (err: any) {
    toast.show(t(lang, 'settings.categories.edit.failPrefix') + (err?.message ?? ''))
  } finally {
    busy.value = false
  }
}

async function handleDelete(c: Category) {
  const confirmed = await new Promise<boolean>(resolve => {
    uni.showModal({
      title: t(lang, 'common.confirm'),
      content: t(lang, 'settings.categories.delete.confirm').replace('{name}', c.name),
      success: res => resolve(res.confirm),
    })
  })
  if (!confirmed) return
  busy.value = true
  try {
    await deleteCategory(c.id)
    toast.show(t(lang, 'settings.categories.delete.success'))
    await loadCategories()
  } catch (err: any) {
    toast.show(t(lang, 'settings.categories.delete.failPrefix') + (err?.message ?? ''))
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <scroll-view scroll-y class="page">
    <!-- heading -->
    <view class="section">
      <text class="heading">{{ t(lang, 'settings.heading') }}</text>
    </view>

    <!-- top row: user card + system prefs -->
    <view class="row">
      <!-- user card -->
      <view class="card user-card">
        <!-- avatar ring -->
        <view class="avatar-wrap">
          <view class="avatar-circle">
            <image v-if="auth.user?.avatar" :src="auth.user.avatar" class="avatar-img" mode="aspectFill" />
            <text v-else class="avatar-icon">person</text>
          </view>
        </view>

        <view v-if="auth.user" class="user-info">
          <text class="display-name">{{ auth.user.displayName || auth.user.username }}</text>
          <text class="info-line">{{ t(lang, 'settings.userCard.accountLabel') }}：{{ auth.user.username }}</text>
          <text class="info-line">{{ t(lang, 'settings.userCard.freeVersion') }}</text>
          <text class="info-line">{{ t(lang, 'settings.userCard.genderLabel') }}：{{ genderText }}</text>
          <text class="info-line mb-6">{{ t(lang, 'settings.userCard.ageLabel') }}：{{ ageText }}</text>
          <button class="btn-outline" @tap="navigateToEdit">{{ t(lang, 'settings.userCard.editProfile') }}</button>
        </view>
        <view v-else class="user-info">
          <text class="info-line">{{ t(lang, 'settings.userCard.accountLabel') }}：—</text>
        </view>
      </view>

      <!-- system prefs -->
      <view class="card prefs-card">
        <view class="card-header">
          <view class="icon-circle">
            <text class="mat-icon">tune</text>
          </view>
          <text class="card-title">{{ t(lang, 'settings.prefs.title') }}</text>
        </view>

        <!-- theme segmented -->
        <view class="pref-row">
          <view class="pref-label">
            <text class="pref-title">{{ t(lang, 'settings.prefs.theme.label') }}</text>
            <text class="pref-desc">{{ t(lang, 'settings.prefs.theme.desc') }}</text>
          </view>
          <view class="seg-ctrl">
            <view
              v-for="opt in themeOptions" :key="opt.mode"
              :class="['seg-btn', theme.mode === opt.mode ? 'seg-active' : '']"
              @tap="theme.setMode(opt.mode)"
            >
              <text :class="theme.mode === opt.mode ? 'seg-txt-active' : 'seg-txt'">{{ t(lang, opt.labelKey) }}</text>
            </view>
          </view>
        </view>

        <view class="divider" />

        <!-- language picker -->
        <view class="pref-row">
          <view class="pref-label">
            <text class="pref-title">{{ t(lang, 'settings.prefs.lang.label') }}</text>
            <text class="pref-desc">{{ t(lang, 'settings.prefs.lang.desc') }}</text>
          </view>
          <picker mode="selector" :range="LANGS.map(l => l.label)" :value="langIndex" @change="onLangChange">
            <view class="lang-picker">
              <text>{{ LANGS[langIndex]?.label }}</text>
              <text class="mat-icon" style="font-size:20px">expand_more</text>
            </view>
          </picker>
        </view>
      </view>
    </view>

    <!-- categories section -->
    <view class="card">
      <view class="card-header-row">
        <view class="card-header">
          <view class="icon-circle">
            <text class="mat-icon">category</text>
          </view>
          <text class="card-title">{{ t(lang, 'settings.categories.title') }}</text>
        </view>
        <button class="btn-primary-sm" @tap="showNew = !showNew">
          <text class="mat-icon" style="font-size:16px">add</text>
          {{ t(lang, 'settings.categories.create.toggle') }}
        </button>
      </view>

      <!-- tabs -->
      <view class="cat-tabs">
        <view :class="['cat-tab', catTab === 'expense' ? 'cat-tab-active' : '']" @tap="catTab = 'expense'">
          <text>{{ t(lang, 'settings.categories.tab.expense') }}</text>
        </view>
        <view :class="['cat-tab', catTab === 'income' ? 'cat-tab-active' : '']" @tap="catTab = 'income'">
          <text>{{ t(lang, 'settings.categories.tab.income') }}</text>
        </view>
      </view>

      <!-- new category form -->
      <view v-if="showNew" class="new-form">
        <view class="form-row">
          <view class="form-field">
            <text class="field-label">{{ t(lang, 'settings.categories.field.name') }}</text>
            <input v-model="newName" class="form-input" maxlength="20" placeholder="" />
          </view>
          <view class="form-field" style="max-width:120px">
            <text class="field-label">{{ t(lang, 'settings.categories.field.icon') }}</text>
            <input v-model="newIcon" class="form-input" maxlength="32" placeholder="" />
          </view>
          <view class="form-field" style="max-width:80px">
            <text class="field-label">{{ t(lang, 'settings.categories.field.color') }}</text>
            <input v-model="newColor" class="form-input" type="color" style="height:36px" />
          </view>
        </view>
        <view class="form-actions">
          <button class="btn-outline-sm" @tap="showNew = false">{{ t(lang, 'common.cancel') }}</button>
          <button class="btn-primary-sm" :disabled="busy || !newName.trim()" @tap="handleCreate">{{ t(lang, 'common.save') }}</button>
        </view>
      </view>

      <!-- category list -->
      <view class="cat-list">
        <view v-for="c in catItems" :key="c.id" class="cat-item">
          <view class="cat-dot" :style="{ backgroundColor: c.color + '33' }">
            <text style="font-size:16px">{{ c.icon }}</text>
          </view>
          <view class="cat-info">
            <text class="cat-name">{{ c.name }}</text>
            <text class="cat-color">{{ c.color }}</text>
          </view>
          <view class="cat-actions">
            <view v-if="c.isPreset" class="preset-badge">
              <text>{{ t(lang, 'settings.categories.presetBadge') }}</text>
            </view>
            <template v-else>
              <button class="btn-outline-sm" @tap="openEdit(c)">{{ t(lang, 'common.edit') }}</button>
              <button class="btn-danger-sm" :disabled="busy" @tap="handleDelete(c)">{{ t(lang, 'common.delete') }}</button>
            </template>
          </view>
        </view>
        <view v-if="catItems.length === 0" class="empty">
          <text>{{ t(lang, 'common.empty') }}</text>
        </view>
      </view>
    </view>

    <!-- bottom row: about + account security -->
    <view class="row">
      <!-- about -->
      <view class="card about-card">
        <view class="card-header">
          <text class="mat-icon primary-icon" style="font-size:22px">info</text>
          <text class="card-title">{{ t(lang, 'settings.about.title') }}</text>
        </view>
        <view class="about-logo-row">
          <view class="about-logo">
            <text class="about-logo-text">Q</text>
          </view>
          <view>
            <text class="about-version" :busy="versionState === 'loading'">
              {{ versionState === 'loading' ? 'QingZhang v…' : versionState === 'error' ? 'QingZhang v—' : `QingZhang v${version}` }}
            </text>
            <text class="info-line">
              {{ versionState === 'ok' ? t(lang, 'settings.about.currentVersion') : versionState === 'error' ? t(lang, 'settings.about.versionUnavailable') : t(lang, 'settings.about.fetchingVersion') }}
            </text>
          </view>
        </view>
        <view class="about-links">
          <text class="link">{{ t(lang, 'settings.about.terms') }}</text>
          <text class="link">{{ t(lang, 'settings.about.privacy') }}</text>
        </view>
      </view>

      <!-- account security -->
      <view class="card security-card">
        <view class="card-header">
          <text class="mat-icon danger-icon" style="font-size:22px">shield</text>
          <text class="card-title">{{ t(lang, 'settings.accountSecurity.title') }}</text>
        </view>
        <text class="info-line security-desc">{{ t(lang, 'settings.accountSecurity.desc') }}</text>
        <view class="logout-row">
          <button class="btn-logout" @tap="handleLogout">
            <text class="mat-icon" style="font-size:18px">logout</text>
            {{ t(lang, 'settings.accountSecurity.logout') }}
          </button>
        </view>
      </view>
    </view>
  </scroll-view>

  <!-- edit modal -->
  <view v-if="editing" class="modal-mask" @tap.self="editing = null">
    <view class="modal">
      <text class="modal-title">{{ t(lang, 'settings.categories.edit.title') }}</text>
      <view class="form-field">
        <text class="field-label">{{ t(lang, 'settings.categories.field.name') }}</text>
        <input v-model="editName" class="form-input" maxlength="20" />
      </view>
      <view class="form-field">
        <text class="field-label">{{ t(lang, 'settings.categories.field.color') }}</text>
        <input v-model="editColor" class="form-input" type="color" style="height:40px" />
      </view>
      <view class="modal-actions">
        <button class="btn-outline-sm" @tap="editing = null">{{ t(lang, 'common.cancel') }}</button>
        <button class="btn-primary-sm" :disabled="busy" @tap="handleSaveEdit">{{ t(lang, 'common.save') }}</button>
      </view>
    </view>
  </view>
</template>

<style scoped>
.page { height: 100vh; background: var(--c-bg); padding: 24rpx; box-sizing: border-box; }
.section { margin-bottom: 24rpx; }
.heading { font-size: 32rpx; font-weight: 700; color: var(--c-text); }
.row { display: flex; flex-direction: column; gap: 24rpx; margin-bottom: 24rpx; }
.card { background: var(--c-bg-card); border-radius: 16rpx; padding: 32rpx; }

/* user card */
.user-card { display: flex; flex-direction: column; align-items: center; text-align: center; }
.avatar-wrap { margin-bottom: 16rpx; }
.avatar-circle { width: 160rpx; height: 160rpx; border-radius: 50%; background: var(--c-primary-light); display: flex; align-items: center; justify-content: center; overflow: hidden; }
.avatar-img { width: 100%; height: 100%; }
.avatar-icon { font-size: 80rpx; color: var(--c-primary); }
.user-info { width: 100%; }
.display-name { font-size: 36rpx; font-weight: 600; color: var(--c-text); display: block; margin-bottom: 8rpx; }
.info-line { font-size: 26rpx; color: var(--c-text-variant); display: block; margin-bottom: 4rpx; }
.mb-6 { margin-bottom: 24rpx; }
.btn-outline { border: 1px solid var(--c-divider); border-radius: 12rpx; padding: 16rpx; font-size: 28rpx; color: var(--c-text); background: transparent; width: 100%; }

/* prefs card */
.prefs-card {}
.card-header { display: flex; align-items: center; gap: 16rpx; margin-bottom: 32rpx; }
.icon-circle { width: 72rpx; height: 72rpx; border-radius: 50%; background: var(--c-primary-light); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.mat-icon { font-family: 'Material Symbols Outlined'; font-size: 20px; font-weight: normal; font-style: normal; }
.card-title { font-size: 30rpx; font-weight: 600; color: var(--c-text); }
.pref-row { display: flex; align-items: center; justify-content: space-between; padding: 24rpx 0; }
.pref-label {}
.pref-title { font-size: 28rpx; font-weight: 600; color: var(--c-text); display: block; margin-bottom: 4rpx; }
.pref-desc { font-size: 24rpx; color: var(--c-text-variant); }
.divider { height: 1px; background: var(--c-divider); }
.seg-ctrl { display: flex; border: 1px solid var(--c-divider); border-radius: 12rpx; overflow: hidden; background: var(--c-surface); }
.seg-btn { padding: 12rpx 20rpx; transition: all 0.2s; }
.seg-txt { font-size: 24rpx; color: var(--c-text-variant); }
.seg-txt-active { font-size: 24rpx; color: var(--c-text); font-weight: 600; }
.seg-active { background: var(--c-bg-card); }
.lang-picker { display: flex; align-items: center; gap: 8rpx; background: var(--c-surface); border: 1px solid var(--c-divider); border-radius: 12rpx; padding: 12rpx 20rpx; }

/* categories */
.card-header-row { display: flex; align-items: center; justify-content: space-between; margin-bottom: 24rpx; }
.cat-tabs { display: flex; gap: 16rpx; margin-bottom: 16rpx; }
.cat-tab { padding: 12rpx 24rpx; border-radius: 12rpx; font-size: 26rpx; color: var(--c-text-variant); transition: all 0.2s; }
.cat-tab-active { background: var(--c-primary-light); color: var(--c-primary); font-weight: 600; }
.new-form { border: 1px solid var(--c-divider); border-radius: 12rpx; padding: 20rpx; margin-bottom: 16rpx; }
.form-row { display: flex; gap: 16rpx; flex-wrap: wrap; margin-bottom: 16rpx; }
.form-field { display: flex; flex-direction: column; gap: 8rpx; flex: 1; min-width: 100rpx; }
.field-label { font-size: 22rpx; color: var(--c-text-variant); }
.form-input { border: 1px solid var(--c-divider); border-radius: 8rpx; padding: 12rpx; background: var(--c-bg); color: var(--c-text); font-size: 26rpx; }
.form-actions { display: flex; gap: 12rpx; justify-content: flex-end; }
.cat-list {}
.cat-item { display: flex; align-items: center; gap: 16rpx; padding: 16rpx 0; border-top: 1px solid var(--c-divider); }
.cat-dot { width: 64rpx; height: 64rpx; border-radius: 50%; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.cat-info { flex: 1; min-width: 0; }
.cat-name { font-size: 26rpx; color: var(--c-text); display: block; }
.cat-color { font-size: 22rpx; color: var(--c-text-variant); }
.cat-actions { display: flex; align-items: center; gap: 8rpx; flex-shrink: 0; }
.preset-badge { padding: 6rpx 16rpx; border-radius: 999rpx; background: var(--c-surface); font-size: 22rpx; color: var(--c-text-variant); }
.empty { padding: 48rpx 0; text-align: center; font-size: 26rpx; color: var(--c-text-variant); }
.btn-primary-sm { background: var(--c-primary); color: #fff; border-radius: 8rpx; padding: 10rpx 20rpx; font-size: 24rpx; border: none; display: inline-flex; align-items: center; gap: 4rpx; }
.btn-outline-sm { border: 1px solid var(--c-divider); border-radius: 8rpx; padding: 10rpx 20rpx; font-size: 24rpx; color: var(--c-text); background: transparent; }
.btn-danger-sm { border: 1px solid var(--c-error); color: var(--c-error); border-radius: 8rpx; padding: 10rpx 20rpx; font-size: 24rpx; background: transparent; }

/* about */
.about-logo-row { display: flex; gap: 16rpx; margin-bottom: 32rpx; }
.about-logo { width: 112rpx; height: 128rpx; border-radius: 12rpx; background: var(--c-primary-light); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.about-logo-text { font-size: 56rpx; font-weight: 700; color: var(--c-primary); }
.about-version { font-size: 30rpx; font-weight: 600; color: var(--c-text); display: block; margin-bottom: 4rpx; }
.about-links { display: flex; gap: 32rpx; padding-top: 16rpx; border-top: 1px solid var(--c-divider); }
.link { font-size: 26rpx; color: var(--c-primary); }

/* security */
.security-desc { margin-bottom: 32rpx; font-size: 26rpx; color: var(--c-text-variant); line-height: 1.6; }
.logout-row { display: flex; justify-content: flex-end; }
.btn-logout { display: inline-flex; align-items: center; gap: 8rpx; border: 2px solid var(--c-error); color: var(--c-error); border-radius: 12rpx; padding: 16rpx 24rpx; font-size: 28rpx; background: transparent; }
.primary-icon { color: var(--c-primary); }
.danger-icon { color: var(--c-error); }

/* modal */
.modal-mask { position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 999; display: flex; align-items: center; justify-content: center; padding: 32rpx; }
.modal { background: var(--c-bg-card); border-radius: 20rpx; padding: 40rpx; width: 100%; max-width: 600rpx; }
.modal-title { font-size: 32rpx; font-weight: 600; color: var(--c-text); display: block; margin-bottom: 24rpx; }
.modal-actions { display: flex; gap: 16rpx; justify-content: flex-end; margin-top: 24rpx; }
</style>
