// 003.前端代码（前端工程师）/frontend-react/src/components/TransactionRow.tsx
import type { Transaction } from '../data/transactions'
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES, type Category } from '../data/categories'
import type { Account } from '../data/accounts'
import { CategoryBadge } from './CategoryBadge'

interface TransactionRowProps {
  transaction: Transaction
  account: Account | undefined
}

function findCategory(id: string): Category | undefined {
  return [...EXPENSE_CATEGORIES, ...INCOME_CATEGORIES].find((c) => c.id === id)
}

function formatAmount(amount: number, type: 'expense' | 'income'): string {
  const sign = type === 'expense' ? '-' : '+'
  return `${sign}¥${new Intl.NumberFormat('zh-CN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(amount))}`
}

export function TransactionRow({ transaction, account }: TransactionRowProps) {
  const category = findCategory(transaction.categoryId)

  return (
    <div className="flex items-center gap-3 py-3 border-b border-divider last:border-0">
      {category && <CategoryBadge category={category} size="sm" />}

      <div className="flex-1 min-w-0">
        <p className="font-headline-md text-headline-md text-text-primary truncate">
          {transaction.note}
        </p>
        <p className="font-caption-sm text-caption-sm text-on-surface-variant truncate">
          {category?.name}
          {account && <span> · {account.name}</span>}
        </p>
      </div>

      <span
        className={`font-label-mono text-label-mono shrink-0 ${
          transaction.type === 'expense' ? 'text-error' : 'text-secondary'
        }`}
      >
        {formatAmount(transaction.amount, transaction.type)}
      </span>
    </div>
  )
}

// 007.跨端APP应用（移动端开发工程师）/src/components/TransactionRow.vue
<script setup lang="ts">
import type { Record } from '@/api/records'
import { formatAmount } from '@/utils/finance'
import CategoryBadge from './CategoryBadge.vue'
import type { Category } from '@/api/categories'

defineProps<{ record: Record; category?: Category }>()
const emit = defineEmits<{ (e: 'tap', r: Record): void }>()
</script>
<template>
  <view class="row" @tap="emit('tap', record)">
    <view class="left">
      <CategoryBadge v-if="category" :category="category" size="sm" />
      <text v-else class="cat-name">未分类</text>
      <text class="note" v-if="record.note">{{ record.note }}</text>
    </view>
    <view class="right">
      <text :class="['amt', record.type === 'income' ? 'income' : 'expense']">
        {{ record.type === 'income' ? '+' : '-' }}{{ formatAmount(Math.abs(record.amount), false) }}
      </text>
      <text class="date">{{ record.recordDate }}</text>
    </view>
  </view>
</template>
<style scoped>
.row { display: flex; align-items: center; padding: 24rpx 16rpx; border-bottom: 1px solid var(--c-divider); }
.left { flex: 1; display: flex; flex-direction: column; gap: 6rpx; }
.cat-name { font-size: 26rpx; color: var(--c-text-variant); }
.note { font-size: 22rpx; color: var(--c-text-variant); }
.right { text-align: right; display: flex; flex-direction: column; gap: 6rpx; }
.amt.income { color: #2E7DE6; font-weight: 600; }
.amt.expense { color: var(--c-error); font-weight: 600; }
.date { font-size: 22rpx; color: var(--c-text-variant); }
</style>
