// 007.跨端APP应用（移动端开发工程师）/uniapp-project/components/charts/LineChart.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useLanguage } from '@/i18n/useLanguage'

interface Point { day: number; income: number; expense: number }
const props = withDefaults(defineProps<{
  data: Point[]
  incomeColor?: string
  expenseColor?: string
  smoothWindow?: number
}>(), {
  incomeColor: '#005394',
  expenseColor: '#ba1a1a',
  smoothWindow: 5,
})

const { t } = useLanguage()

const W = 800, H = 320
const PAD = { top: 20, right: 20, bottom: 40, left: 50 }
const innerW = W - PAD.left - PAD.right
const innerH = H - PAD.top - PAD.bottom

const hover = ref<{ idx: number; localX: number } | null>(null)
const svgEl = ref<any>(null)

// 平滑(移动平均)对齐 React
function smooth(values: number[], w: number): number[] {
  if (w <= 1) return values
  return values.map((_, i) => {
    const start = Math.max(0, i - w + 1)
    const slice = values.slice(start, i + 1)
    return slice.reduce((s, v) => s + v, 0) / slice.length
  })
}

const YMAX = 4000

const xs = computed(() => props.data.map((_, i) => PAD.left + (i / Math.max(1, props.data.length - 1)) * innerW))
const ys = (v: number) => PAD.top + innerH - (v / YMAX) * innerH

// Catmull-Rom → 三次贝塞尔(简化版),对齐 React
function smoothPath(values: number[]): string {
  if (values.length === 0) return ''
  const pts = values.map((v, i) => ({ x: xs.value[i], y: ys(v) }))
  let d = `M ${pts[0].x},${pts[0].y}`
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[i - 1] ?? pts[i]
    const p1 = pts[i]
    const p2 = pts[i + 1]
    const p3 = pts[i + 2] ?? p2
    const cp1x = p1.x + (p2.x - p0.x) / 6
    const cp1y = p1.y + (p2.y - p0.y) / 6
    const cp2x = p2.x - (p3.x - p1.x) / 6
    const cp2y = p2.y - (p3.y - p1.y) / 6
    d += ` C ${cp1x},${cp1y} ${cp2x},${cp2y} ${p2.x},${p2.y}`
  }
  return d
}

const lineIncome = computed(() => {
  const sm = smooth(props.data.map(d => d.income), props.smoothWindow)
  return smoothPath(sm.map(v => Math.min(v, YMAX)))
})
const lineExpense = computed(() => {
  const sm = smooth(props.data.map(d => d.expense), props.smoothWindow)
  return smoothPath(sm.map(v => Math.min(v, YMAX)))
})
// 收入曲线下方填充
const incomeArea = computed(() => {
  if (props.data.length === 0) return ''
  const first = xs.value[0]
  const last = xs.value[xs.value.length - 1]
  return lineIncome.value + ` L ${last},${ys(0)} L ${first},${ys(0)} Z`
})

const yTicks = [0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
const xTicks = [1, 5, 10, 15, 20, 25, 30]

function pickIdx(clientX: number): number | null {
  const svg = svgEl.value
  if (!svg) return null
  // uni-app svg 用 getBoundingClientRect 在 h5/weapp 都可用
  const rect = svg.getBoundingClientRect ? svg.getBoundingClientRect() : null
  if (!rect || rect.width === 0) return null
  const vbX = ((clientX - rect.left) / rect.width) * W
  if (vbX < PAD.left - 10 || vbX > W - PAD.right + 10) return null
  const ratio = (vbX - PAD.left) / innerW
  const day = Math.round(ratio * (props.data.length - 1)) + 1
  return Math.max(0, Math.min(props.data.length - 1, day - 1))
}

function onTouch(e: any) {
  const touches = e?.touches?.[0]
  if (!touches) return
  const svg = svgEl.value
  if (!svg) return
  const offsetX = touches.x ?? touches.clientX ?? touches.pageX
  const idx = pickIdx(offsetX)
  if (idx === null) return
  // 转成相对 .line-wrap 的本地坐标(absolute 子元素需要这个)
  const rect = svg.getBoundingClientRect()
  hover.value = { idx, localX: offsetX - rect.left }
}
function onTouchEnd() {
  // 保持显示一段时间,让用户看清
  setTimeout(() => { hover.value = null }, 1500)
}
function clearHover() { hover.value = null }

const hoverData = computed(() => hover.value ? props.data[hover.value.idx] : null)
const hoverVbX = computed(() => hover.value ? xs.value[hover.value.idx] : 0)
// tooltip 顶部位置(以 max(income, expense) 为锚点),转换为相对 SVG 的百分比
const hoverTopPct = computed(() => {
  if (!hoverData.value || !hover.value) return '50%'
  const yVal = Math.max(hoverData.value.income, hoverData.value.expense)
  return `${(ys(Math.min(yVal, YMAX)) / H) * 100}%`
})
// tooltip 锚点:触点在右半用右对齐(-100%)避免溢出 chart card,左半居中
const tipAnchor = computed(() => {
  if (!hover.value || !svgEl.value) return 'center'
  const rect = svgEl.value.getBoundingClientRect()
  return hover.value.localX > rect.width / 2 ? 'right' : 'center'
})
</script>

<template>
  <view class="line-wrap">
    <svg ref="svgEl" :viewBox="`0 0 ${W} ${H}`" preserveAspectRatio="xMidYMid meet"
         @touchstart="onTouch" @touchmove="onTouch" @touchend="onTouchEnd">
      <!-- 网格线 -->
      <g v-for="v in yTicks" :key="v">
        <line :x1="PAD.left" :x2="W - PAD.right" :y1="ys(v)" :y2="ys(v)"
              stroke="#E2E8F0" stroke-width="1" />
      </g>
      <!-- 收入填充 -->
      <path :d="incomeArea" :fill="incomeColor" fill-opacity="0.1" />
      <!-- 收入曲线 -->
      <path :d="lineIncome" :stroke="incomeColor" fill="none"
            stroke-width="2" stroke-linejoin="round" stroke-linecap="round" />
      <!-- 支出曲线 -->
      <path :d="lineExpense" :stroke="expenseColor" fill="none"
            stroke-width="2" stroke-linejoin="round" stroke-linecap="round" />
      <!-- 悬停十字虚线 -->
      <line v-if="hover" :x1="hoverVbX" :x2="hoverVbX"
            :y1="PAD.top" :y2="H - PAD.bottom"
            stroke="#94a3b8" stroke-width="1" stroke-dasharray="3 3" />
      <!-- 悬停数据点圆环 -->
      <template v-if="hoverData">
        <circle :cx="hoverVbX" :cy="ys(Math.min(hoverData.income, YMAX))" r="5"
                fill="#fff" :stroke="incomeColor" stroke-width="2" />
        <circle :cx="hoverVbX" :cy="ys(Math.min(hoverData.expense, YMAX))" r="5"
                fill="#fff" :stroke="expenseColor" stroke-width="2" />
      </template>
    </svg>
    <!-- 轴标签:HTML 覆盖层(SVG text 在 H5 渲染不稳定,改用 HTML 定位,百分比跟 viewBox 对齐) -->
    <text v-for="v in yTicks" :key="`y-${v}`" class="axis-y"
          :style="{ left: (PAD.left / W * 100) + '%', top: (ys(v) / H * 100) + '%' }">
      {{ v.toLocaleString('en-US') }}
    </text>
    <text v-for="d in xTicks" :key="`x-${d}`" class="axis-x"
          :style="{ left: (xs[d - 1] / W * 100) + '%', top: ((H - PAD.bottom + 18) / H * 100) + '%' }">
      {{ d }}
    </text>
    <!-- Tooltip(HTML 覆盖层,跟随触点位置) -->
    <view v-if="hoverData && hover" class="tip" :class="`tip-${tipAnchor}`"
          :style="{ left: hover.localX + 'px', top: hoverTopPct }">
      <view class="tip-day">{{ hoverData.day }}</view>
      <view class="tip-row">
        <view class="tip-swatch" :style="{ borderColor: incomeColor }" />
        <text class="tip-text">{{ t('chart.line.income') }}: {{ Math.round(hoverData.income).toLocaleString('en-US') }}</text>
      </view>
      <view class="tip-row">
        <view class="tip-swatch" :style="{ borderColor: expenseColor }" />
        <text class="tip-text">{{ t('chart.line.expense') }}: {{ Math.round(hoverData.expense).toLocaleString('en-US') }}</text>
      </view>
    </view>
  </view>
</template>

<style scoped>
.line-wrap { position: relative; width: 100%; }
svg { width: 100%; height: auto; display: block; }
/* 轴标签(HTML 覆盖层,SVG text 在 H5 不稳) */
.axis-y {
  position: absolute;
  transform: translate(-100%, -50%);
  font-size: 11px;
  color: #64748b;
  line-height: 1;
  white-space: nowrap;
  pointer-events: none;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
.axis-x {
  position: absolute;
  transform: translate(-50%, 0);
  font-size: 11px;
  color: #64748b;
  line-height: 1;
  pointer-events: none;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
.tip {
  position: absolute; transform: translate(-50%, -110%);
  background: var(--c-bg-card); border: 1px solid var(--c-divider);
  border-radius: 8rpx; padding: 12rpx 16rpx; font-size: 22rpx; color: var(--c-text);
  box-shadow: 0 4rpx 12rpx rgba(0, 0, 0, 0.08);
  pointer-events: none; min-width: 140rpx;
}
.tip-right { transform: translate(-100%, -110%); }
.tip-day { font-weight: 700; font-size: 24rpx; margin-bottom: 4rpx; color: var(--c-text); }
.tip-row { display: flex; align-items: center; gap: 8rpx; margin-top: 4rpx; }
.tip-swatch { width: 10rpx; height: 10rpx; background: transparent; border: 2rpx solid; border-radius: 2rpx; }
.tip-text { font-size: 22rpx; color: var(--c-text); }
</style>

// 003.前端代码（前端工程师）/frontend-react-java/src/components/LineChart.tsx
import { useLayoutEffect, useMemo, useRef, useState } from 'react'
import { useLanguage } from '../i18n/LanguageContext'

interface LineChartProps {
  data: Array<{ day: number; income: number; expense: number }>
  /** 颜色：收入（蓝）/ 支出（红） */
  incomeColor?: string
  expenseColor?: string
  /** 平滑窗口大小（天）。0=不平滑。默认 5 */
  smoothWindow?: number
}

interface HoverInfo {
  idx: number
  clientX: number
}

/**
 * 每日收支趋势折线图（纯 SVG，平滑曲线 + 触摸/鼠标交互）
 * - X 轴：1 / 5 / 10 / 15 / 20 / 25 / 30 天
 * - Y 轴：硬编码 0–4000（与原型一致）
 * - 悬停 / 触摸时：显示十字线 + 数据点圆环 + 浮动 tooltip
 */
export function LineChart({
  data,
  incomeColor = '#005394',
  expenseColor = '#ba1a1a',
  smoothWindow = 5,
}: LineChartProps) {
  const { t } = useLanguage()
  const W = 800
  const H = 320
  const PADDING = { top: 20, right: 20, bottom: 40, left: 50 }
  const innerW = W - PADDING.left - PADDING.right
  const innerH = H - PADDING.top - PADDING.bottom
  const svgRef = useRef<SVGSVGElement>(null)
  const [hover, setHover] = useState<HoverInfo | null>(null)
  // 记录 SVG 的实际渲染尺寸(viewport 像素),用来精确放置 tooltip
  const [svgBox, setSvgBox] = useState<{ left: number; top: number; w: number; h: number } | null>(null)

  // 移动平均平滑（默认 5 天窗口），让稀疏数据呈现连续曲线
  const smoothed = useMemo(() => {
    if (smoothWindow <= 1) return data
    return data.map((d, i) => {
      const start = Math.max(0, i - smoothWindow + 1)
      const slice = data.slice(start, i + 1)
      const inc = slice.reduce((s, x) => s + x.income, 0) / slice.length
      const exp = slice.reduce((s, x) => s + x.expense, 0) / slice.length
      return { day: d.day, income: inc, expense: exp }
    })
  }, [data, smoothWindow])

  // Y 轴硬编码 0–4000（与原型一致）
  const yMax = 4000

  const xFor = (day: number) =>
    PADDING.left + ((day - 1) / 29) * innerW
  const yFor = (val: number) =>
    PADDING.top + innerH - (val / yMax) * innerH

  // 平滑路径（Catmull-Rom → Bezier 简化版）
  function smoothPath(values: number[]): string {
    if (values.length === 0) return ''
    const pts = values.map((v, i) => ({ x: xFor(i + 1), y: yFor(v) }))
    let d = `M ${pts[0].x},${pts[0].y}`
    for (let i = 0; i < pts.length - 1; i++) {
      const p0 = pts[i - 1] ?? pts[i]
      const p1 = pts[i]
      const p2 = pts[i + 1]
      const p3 = pts[i + 2] ?? p2
      const cp1x = p1.x + (p2.x - p0.x) / 6
      const cp1y = p1.y + (p2.y - p0.y) / 6
      const cp2x = p2.x - (p3.x - p1.x) / 6
      const cp2y = p2.y - (p3.y - p1.y) / 6
      d += ` C ${cp1x},${cp1y} ${cp2x},${cp2y} ${p2.x},${p2.y}`
    }
    return d
  }

  const incomeValues = smoothed.map((d) => Math.min(d.income, yMax))
  const expenseValues = smoothed.map((d) => Math.min(d.expense, yMax))
  const incomePath = smoothPath(incomeValues)
  const expensePath = smoothPath(expenseValues)

  // 填充区域（收入曲线下方）
  const incomeArea =
    incomePath + ` L ${xFor(30)},${yFor(0)} L ${xFor(1)},${yFor(0)} Z`

  const yTicks = [0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
  const xTicks = [1, 5, 10, 15, 20, 25, 30]

  /** 把鼠标 / 触摸 X 坐标转换为最近的数据点索引 */
  function pickIdx(clientX: number): number | null {
    const svg = svgRef.current
    if (!svg) return null
    const rect = svg.getBoundingClientRect()
    if (rect.width === 0) return null
    // 将 clientX 映射到 viewBox 的 X
    const vbX = ((clientX - rect.left) / rect.width) * W
    if (vbX < PADDING.left - 10 || vbX > W - PADDING.right + 10) return null
    const ratio = (vbX - PADDING.left) / innerW
    const day = Math.round(ratio * 29) + 1
    return Math.max(0, Math.min(29, day - 1))
  }

  function onMouseMove(e: React.MouseEvent<SVGSVGElement>) {
    const idx = pickIdx(e.clientX)
    setHover(idx === null ? null : { idx, clientX: e.clientX })
  }
  function onMouseLeave() {
    setHover(null)
  }
  function onTouchMove(e: React.TouchEvent<SVGSVGElement>) {
    if (e.touches.length > 0) {
      const idx = pickIdx(e.touches[0].clientX)
      setHover(idx === null ? null : { idx, clientX: e.touches[0].clientX })
    }
  }
  function onTouchEnd() {
    // 保持显示一段时间，让用户看清
    window.setTimeout(() => setHover(null), 1500)
  }

  const hoverData = hover ? smoothed[hover.idx] : null
  const hoverVbX = hover ? xFor(hover.idx + 1) : 0

  // 每次 hover / resize 触发时,刷新 SVG 的 viewport 包围盒
  useLayoutEffect(() => {
    if (!svgRef.current) return
    const update = () => {
      const r = svgRef.current!.getBoundingClientRect()
      setSvgBox({ left: r.left, top: r.top, w: r.width, h: r.height })
    }
    update()
    window.addEventListener('resize', update)
    window.addEventListener('scroll', update, true)
    return () => {
      window.removeEventListener('resize', update)
      window.removeEventListener('scroll', update, true)
    }
  }, [hover])

  return (
    <div className="relative">
      <svg
        ref={svgRef}
        viewBox={`0 0 ${W} ${H}`}
        className="w-full h-auto select-none"
        preserveAspectRatio="xMidYMid meet"
        onMouseMove={onMouseMove}
        onMouseLeave={onMouseLeave}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}
      >
        {/* 网格线 + Y 轴标签 */}
        {yTicks.map((v) => (
          <g key={v}>
            <line
              x1={PADDING.left}
              y1={yFor(v)}
              x2={W - PADDING.right}
              y2={yFor(v)}
              stroke="#E2E8F0"
              strokeWidth="1"
            />
            <text
              x={PADDING.left - 8}
              y={yFor(v)}
              textAnchor="end"
              dominantBaseline="middle"
              fontSize="11"
              fill="#94a3b8"
            >
              {v.toLocaleString('en-US')}
            </text>
          </g>
        ))}

        {/* X 轴标签 */}
        {xTicks.map((d) => (
          <text
            key={d}
            x={xFor(d)}
            y={H - PADDING.bottom + 18}
            textAnchor="middle"
            fontSize="11"
            fill="#94a3b8"
          >
            {d}
          </text>
        ))}

        {/* 收入填充 */}
        <path d={incomeArea} fill={incomeColor} fillOpacity="0.1" />
        {/* 收入曲线 */}
        <path
          d={incomePath}
          stroke={incomeColor}
          strokeWidth="2"
          fill="none"
          strokeLinejoin="round"
          strokeLinecap="round"
        />
        {/* 支出曲线 */}
        <path
          d={expensePath}
          stroke={expenseColor}
          strokeWidth="2"
          fill="none"
          strokeLinejoin="round"
          strokeLinecap="round"
        />

        {/* 悬停十字虚线 */}
        {hover !== null && (
          <line
            x1={hoverVbX}
            y1={PADDING.top}
            x2={hoverVbX}
            y2={H - PADDING.bottom}
            stroke="#94a3b8"
            strokeWidth="1"
            strokeDasharray="3 3"
          />
        )}

        {/* 悬停数据点圆环 */}
        {hoverData && (
          <g>
            <circle
              cx={hoverVbX}
              cy={yFor(Math.min(hoverData.income, yMax))}
              r="5"
              fill="#fff"
              stroke={incomeColor}
              strokeWidth="2"
            />
            <circle
              cx={hoverVbX}
              cy={yFor(Math.min(hoverData.expense, yMax))}
              r="5"
              fill="#fff"
              stroke={expenseColor}
              strokeWidth="2"
            />
          </g>
        )}
      </svg>

      {/* Tooltip(HTML 覆盖层,使用 viewport 像素 + position:fixed,避开任何容器裁剪) */}
      {hoverData && hover && svgBox && (() => {
        const maxVal = Math.max(hoverData.income, hoverData.expense, 1)
        // 数据点靠近顶部时,把 tooltip 翻到点的下方,避免被推到屏幕外
        const isNearTop = maxVal / yMax > 0.7
        // viewBox 坐标 → viewport 像素(viewBox 0..W/H → svgBox 包围盒)
        const dataVbY = yFor(Math.min(maxVal, yMax))
        const dataPxX = svgBox.left + (hoverVbX / W) * svgBox.w
        const dataPxY = svgBox.top + (dataVbY / H) * svgBox.h
        return (
          <div
            className="pointer-events-none bg-bg-card border border-divider rounded-lg shadow-lg px-3 py-2 z-50"
            style={{
              position: 'fixed',
              left: `${dataPxX}px`,
              top: isNearTop ? `${dataPxY + 18}px` : `${dataPxY - 14}px`,
              transform: 'translateX(-50%)',
              minWidth: '120px',
            }}
          >
            <div className="font-bold text-text-primary text-xs mb-1">{hoverData.day}</div>
            <div className="flex items-center gap-2 text-xs">
              <span
                className="inline-block w-2.5 h-2.5"
                style={{
                  background: 'transparent',
                  border: `1.5px solid ${incomeColor}`,
                }}
              />
              <span className="text-text-primary">
                {t('chart.line.income')}: {Math.round(hoverData.income).toLocaleString('en-US')}
              </span>
            </div>
            <div className="flex items-center gap-2 text-xs">
              <span
                className="inline-block w-2.5 h-2.5"
                style={{
                  background: 'transparent',
                  border: `1.5px solid ${expenseColor}`,
                }}
              />
              <span className="text-text-primary">
                {t('chart.line.expense')}: {Math.round(hoverData.expense).toLocaleString('en-US')}
              </span>
            </div>
          </div>
        )
      })()}
    </div>
  )
}
