// 007.跨端APP应用（移动端开发工程师）/uniapp-project/components/DonutChart.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useLanguage } from '@/i18n/useLanguage'

interface Segment { label: string; value: number; color: string }
const props = withDefaults(defineProps<{
  segments: Segment[]
  totalLabel?: string
  totalValue: string
  hideLegend?: boolean
}>(), {
  totalLabel: '',
  hideLegend: false,
  size: 200,
  strokeWidth: 24,
})

const { t } = useLanguage()
const finalTotalLabel = computed(() => props.totalLabel || t('chart.donutTotal'))

const radius = 70
const inner = 40
const cx = 100, cy = 100
const W = 200, H = 200

const hoverIdx = ref<number | null>(null)
let touchTimer: ReturnType<typeof setTimeout> | null = null

const arcs = computed(() => {
  const total = props.segments.reduce((s, x) => s + x.value, 0) || 1
  let acc = 0
  return props.segments.map((s, i) => {
    const start = (acc / total) * Math.PI * 2 - Math.PI / 2
    acc += s.value
    let end = (acc / total) * Math.PI * 2 - Math.PI / 2
    // 单个 segment 占 100% 时 start(=-π/2) 与 end(=3π/2) 是同一方向,
    // SVG 弧线从同一点回到同一点会塌陷不渲染;直接让它绕整圈减去极小角度
    if (props.segments.length === 1) {
      end = start + Math.PI * 2 - 0.001
    }
    const mid = (start + end) / 2
    const large = end - start > Math.PI ? 1 : 0
    const x1 = cx + radius * Math.cos(start), y1 = cy + radius * Math.sin(start)
    const x2 = cx + radius * Math.cos(end),   y2 = cy + radius * Math.sin(end)
    const ix1 = cx + inner * Math.cos(end),   iy1 = cy + inner * Math.sin(end)
    const ix2 = cx + inner * Math.cos(start), iy2 = cy + inner * Math.sin(start)
    // tooltip 锚点:圆环外侧一段距离,百分比定位随容器缩放
    const tipR = radius + 12
    const tipX = ((cx + Math.cos(mid) * tipR) / W) * 100
    const tipY = ((cy + Math.sin(mid) * tipR) / H) * 100
    return {
      d: `M ${x1} ${y1} A ${radius} ${radius} 0 ${large} 1 ${x2} ${y2} L ${ix1} ${iy1} A ${inner} ${inner} 0 ${large} 0 ${ix2} ${iy2} Z`,
      color: s.color, label: s.label, value: s.value,
      pct: ((s.value / total) * 100).toFixed(1),
      tipX, tipY,
    }
  })
})

function onTap(i: number) {
  hoverIdx.value = i
  if (touchTimer) clearTimeout(touchTimer)
  // 触摸后保持 2s 显示(对齐 React)
  touchTimer = setTimeout(() => { hoverIdx.value = null; touchTimer = null }, 2000)
}
function clearHover() {
  hoverIdx.value = null
  if (touchTimer) { clearTimeout(touchTimer); touchTimer = null }
}
</script>

<template>
  <view class="wrap">
    <view class="donut-wrap" @tap="clearHover">
      <svg :viewBox="`0 0 ${W} ${H}`" preserveAspectRatio="xMidYMid meet" class="donut-svg">
        <path v-for="(a, i) in arcs" :key="i"
              :d="a.d"
              :fill="a.color"
              :class="['seg', { active: hoverIdx === i }]"
              @tap.stop="onTap(i)"
              @touchstart.stop="onTap(i)" />
      </svg>
      <!-- 中心文字(SVG text 在 H5 不渲染,改 HTML 覆盖层) -->
      <view class="center-text">
        <text class="total-label">{{ finalTotalLabel }}</text>
        <text class="total-value">{{ totalValue }}</text>
      </view>
      <!-- 扇区 tooltip(对齐 React:外侧定位 + 颜色边框小方块 + 类别/金额/百分比) -->
      <view v-if="hoverIdx !== null && arcs[hoverIdx]" class="seg-tip"
            :style="{ left: arcs[hoverIdx].tipX + '%', top: arcs[hoverIdx].tipY + '%' }">
        <view class="seg-tip-row">
          <view class="seg-tip-dot" :style="{ borderColor: arcs[hoverIdx].color }" />
          <text class="seg-tip-label">{{ arcs[hoverIdx].label }}</text>
        </view>
        <text class="seg-tip-value">¥{{ Math.round(arcs[hoverIdx].value).toLocaleString('en-US') }}</text>
        <text class="seg-tip-pct">{{ arcs[hoverIdx].pct }}%</text>
      </view>
    </view>
    <view v-if="!hideLegend" class="legend">
      <view v-for="(a, i) in arcs" :key="i" class="lg-row">
        <view class="dot" :style="{ background: a.color }" />
        <text class="lg-label">{{ a.label }}</text>
        <text class="lg-pct">{{ a.pct }}%</text>
      </view>
    </view>
  </view>
</template>

<style scoped>
.wrap { display: flex; flex-direction: column; align-items: stretch; gap: 24rpx; width: 100%; }
.donut-wrap { position: relative; width: 100%; padding-bottom: 100%; height: 0; margin-top: -60rpx; }
.donut-svg { position: absolute; inset: 0; width: 100%; height: 100%; display: block; }
.seg { transition: opacity 0.15s ease-out; }
.seg.active { opacity: 0.85; }
.center-text {
  position: absolute; inset: 0;
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  pointer-events: none;
}
.total-label { font-size: 22rpx; color: var(--c-text-variant); }
.total-value { font-size: 32rpx; font-weight: 700; color: var(--c-text); margin-top: 4rpx; }
.seg-tip {
  position: absolute;
  transform: translate(-50%, -50%);
  background: var(--c-bg-card);
  border: 1px solid var(--c-divider);
  border-radius: 12rpx;
  padding: 12rpx 16rpx;
  min-width: 140rpx;
  box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.12);
  pointer-events: none;
  z-index: 10;
}
.seg-tip-row { display: flex; align-items: center; gap: 8rpx; margin-bottom: 6rpx; }
.seg-tip-dot { width: 12rpx; height: 12rpx; background: transparent; border: 2rpx solid; border-radius: 2rpx; }
.seg-tip-label { font-size: 22rpx; font-weight: 700; color: var(--c-text); }
.seg-tip-value { display: block; font-size: 22rpx; color: var(--c-text); margin-top: 2rpx; }
.seg-tip-pct { display: block; font-size: 20rpx; color: var(--c-text-variant); margin-top: 4rpx; }
.legend { width: 100%; }
.lg-row { display: flex; align-items: center; gap: 12rpx; padding: 8rpx 0; }
.dot { width: 16rpx; height: 16rpx; border-radius: 50%; }
.lg-label { flex: 1; font-size: 26rpx; color: var(--c-text); }
.lg-pct { font-size: 24rpx; color: var(--c-text-variant); }
</style>

// 003.前端代码（前端工程师）/frontend-react/src/components/DonutChart.tsx
import { useMemo, useRef, useState } from 'react'

export interface DonutSegment {
  label: string
  value: number
  color: string
}

interface DonutChartProps {
  segments: DonutSegment[]
  totalLabel?: string
  totalValue: string
}

interface SegmentGeom {
  /** 该段长度（用于在 stroke-dasharray 上精确绘制） */
  length: number
  /** tooltip 锚点 X（百分比，相对 SVG viewBox） */
  tipX: number
  /** tooltip 锚点 Y（百分比） */
  tipY: number
}

/**
 * 支出占比环形图（纯 SVG + 触摸/鼠标交互）
 * - segments 按 value 排序后顺时针排列
 * - 中心展示 totalLabel + totalValue
 * - 悬停 / 触摸扇区：放大描边宽度 + 弹出分类 tooltip
 */
export function DonutChart({
  segments,
  totalLabel = '总计',
  totalValue,
}: DonutChartProps) {
  const size = 280
  const stroke = 36
  const radius = (size - stroke) / 2
  const cx = size / 2
  const cy = size / 2
  const circumference = 2 * Math.PI * radius
  const svgRef = useRef<SVGSVGElement>(null)
  const [hoverIdx, setHoverIdx] = useState<number | null>(null)
  const touchTimerRef = useRef<number | null>(null)

  const total = segments.reduce((s, x) => s + x.value, 0) || 1

  // 计算每段 tooltip 锚点（圆环外侧），用百分比定位便于随容器缩放
  const geoms = useMemo<SegmentGeom[]>(() => {
    let cursor = 0
    const tipR = radius + stroke / 2 + 18
    return segments.map((seg) => {
      const length = (seg.value / total) * circumference
      const midLen = cursor + length / 2
      const angle = (midLen / circumference) * 2 * Math.PI
      const visualAngle = angle - Math.PI / 2
      const tipX = ((cx + Math.cos(visualAngle) * tipR) / size) * 100
      const tipY = ((cy + Math.sin(visualAngle) * tipR) / size) * 100
      cursor += length
      return { length, tipX, tipY }
    })
  }, [segments, total, radius, stroke, cx, cy, circumference, size])

  function clearTouchTimer() {
    if (touchTimerRef.current !== null) {
      window.clearTimeout(touchTimerRef.current)
      touchTimerRef.current = null
    }
  }

  function onTouchStart(i: number, e: React.TouchEvent) {
    e.preventDefault()
    clearTouchTimer()
    setHoverIdx(i)
    // 触摸后保持 2s 显示
    touchTimerRef.current = window.setTimeout(() => {
      setHoverIdx(null)
      touchTimerRef.current = null
    }, 2000)
  }

  let offset = 0
  return (
    <div className="relative inline-block">
      <svg
        ref={svgRef}
        viewBox={`0 0 ${size} ${size}`}
        className="w-full max-w-[280px] h-auto select-none"
        preserveAspectRatio="xMidYMid meet"
      >
        {/* 背景圈 */}
        <circle
          cx={cx}
          cy={cy}
          r={radius}
          fill="none"
          stroke="#F1F5F9"
          strokeWidth={stroke}
        />
        <g transform={`rotate(-90 ${cx} ${cy})`}>
          {segments.map((seg, i) => {
            const length = (seg.value / total) * circumference
            const dashArray = `${length} ${circumference - length}`
            const dashOffset = -offset
            offset += length
            const isHover = hoverIdx === i
            return (
              <g key={i}>
                {/* 透明命中层（更宽的描边，方便触摸/悬停） */}
                <circle
                  cx={cx}
                  cy={cy}
                  r={radius}
                  fill="none"
                  stroke={seg.color}
                  strokeWidth={stroke + 18}
                  strokeDasharray={dashArray}
                  strokeDashoffset={dashOffset}
                  opacity={0}
                  style={{ cursor: 'pointer', pointerEvents: 'stroke' }}
                  onMouseEnter={() => setHoverIdx(i)}
                  onMouseLeave={() => setHoverIdx(null)}
                  onTouchStart={(e) => onTouchStart(i, e)}
                />
                {/* 可见扇区 */}
                <circle
                  cx={cx}
                  cy={cy}
                  r={radius}
                  fill="none"
                  stroke={seg.color}
                  strokeWidth={isHover ? stroke + 4 : stroke}
                  strokeDasharray={dashArray}
                  strokeDashoffset={dashOffset}
                  strokeLinecap="butt"
                  pointerEvents="none"
                  style={{ transition: 'stroke-width 0.15s ease-out' }}
                />
              </g>
            )
          })}
        </g>
      </svg>

      {/* 中心文字 */}
      <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
        <span className="font-caption-sm text-caption-sm text-on-surface-variant">
          {totalLabel}
        </span>
        <span className="font-label-mono text-label-mono text-text-primary text-2xl font-bold">
          {totalValue}
        </span>
      </div>

      {/* 扇区 tooltip */}
      {hoverIdx !== null && geoms[hoverIdx] && (
        <div
          className="absolute pointer-events-none z-10 bg-bg-card border border-divider rounded-lg shadow-lg px-3 py-2 min-w-[120px] -translate-x-1/2 -translate-y-1/2"
          style={{
            left: `${geoms[hoverIdx].tipX}%`,
            top: `${geoms[hoverIdx].tipY}%`,
          }}
        >
          <div className="flex items-center gap-2 mb-1">
            <span
              className="inline-block w-2.5 h-2.5"
              style={{
                background: 'transparent',
                border: `1.5px solid ${segments[hoverIdx].color}`,
              }}
            />
            <span className="text-xs font-bold text-text-primary">
              {segments[hoverIdx].label}
            </span>
          </div>
          <div className="text-xs text-text-primary">
            ${segments[hoverIdx].value.toLocaleString('en-US', { maximumFractionDigits: 0 })}
          </div>
          <div className="text-xs text-on-surface-variant">
            {((segments[hoverIdx].value / total) * 100).toFixed(1)}%
          </div>
        </div>
      )}
    </div>
  )
}
