// 003.前端代码（前端工程师）/frontend-react/src/pages/Transactions.tsx
import { useMemo, useState } from 'react'
import { usePageTitle, usePageBack } from '../components/PageTitleContext'
import { ACCOUNTS } from '../data/accounts'
import { TRANSACTIONS } from '../data/transactions'
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES } from '../data/categories'
import { TransactionRow } from '../components/TransactionRow'

function findAccount(id: string) {
  return ACCOUNTS.find((a) => a.id === id)
}

const WEEKDAYS = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']

function formatMoney(amount: number): string {
  return new Intl.NumberFormat('zh-CN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(amount))
}

function formatMonth(month: string): string {
  const [y, m] = month.split('-')
  return `${y}年 ${parseInt(m, 10)}月`
}

function formatDayWithWeekday(iso: string): string {
  const d = new Date(iso)
  return `${d.getMonth() + 1}月${d.getDate()}日，${WEEKDAYS[d.getDay()]}`
}

export function Transactions() {
  usePageTitle('全部交易')
  usePageBack('/', '首页')

  const [filterMonth, setFilterMonth] = useState<string>('2026-08')
  const [filterCategory, setFilterCategory] = useState<string>('all')
  const [filterAccount, setFilterAccount] = useState<string>('all')

  const allCategories = useMemo(
    () => [...EXPENSE_CATEGORIES, ...INCOME_CATEGORIES],
    [],
  )

  const filteredTxns = useMemo(() => {
    return TRANSACTIONS.filter((t) => {
      if (filterCategory !== 'all' && t.categoryId !== filterCategory) return false
      if (filterAccount !== 'all' && t.accountId !== filterAccount) return false
      if (!t.date.startsWith(filterMonth)) return false
      return true
    }).sort((a, b) => (a.date < b.date ? 1 : -1))
  }, [filterMonth, filterCategory, filterAccount])

  const { income, expense } = useMemo(() => {
    let inc = 0
    let exp = 0
    for (const t of filteredTxns) {
      if (t.type === 'income') inc += t.amount
      else exp += t.amount
    }
    return { income: inc, expense: exp }
  }, [filteredTxns])
  const net = income - expense

  const groupedTxns = useMemo(() => {
    const groups = new Map<string, typeof filteredTxns>()
    for (const t of filteredTxns) {
      const arr = groups.get(t.date) ?? []
      arr.push(t)
      groups.set(t.date, arr)
    }
    return Array.from(groups.entries()).map(([date, txns]) => {
      const groupNet = txns.reduce(
        (s, t) => s + (t.type === 'income' ? t.amount : -t.amount),
        0,
      )
      return { date, txns, net: groupNet, label: formatDayWithWeekday(date) }
    })
  }, [filteredTxns])

  return (
    <div className="space-y-6">
      {/* Bento grid: filter card + summary card (50/50 split) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Filter card */}
        <div className="bg-bg-card rounded-xl border border-divider p-4 flex flex-col justify-center">
          <h2 className="font-headline-md text-headline-md text-text-primary mb-4">筛选</h2>
          <div className="flex flex-wrap gap-3">
            <select
              className="bg-surface-container-lowest border border-outline-variant text-text-primary text-body-md font-body-md rounded-lg py-2 pl-3 pr-8 focus:border-primary focus:ring-0 cursor-pointer"
              value={filterMonth}
              onChange={(e) => setFilterMonth(e.target.value)}
            >
              <option value="2026-08">{formatMonth('2026-08')}</option>
              <option value="2026-07">{formatMonth('2026-07')}</option>
              <option value="2026-06">{formatMonth('2026-06')}</option>
            </select>

            <select
              className="bg-surface-container-lowest border border-outline-variant text-text-primary text-body-md font-body-md rounded-lg py-2 pl-3 pr-8 focus:border-primary focus:ring-0 cursor-pointer"
              value={filterCategory}
              onChange={(e) => setFilterCategory(e.target.value)}
            >
              <option value="all">所有分类</option>
              {allCategories.map((cat) => (
                <option key={cat.id} value={cat.id}>
                  {cat.name}
                </option>
              ))}
            </select>

            <select
              className="bg-surface-container-lowest border border-outline-variant text-text-primary text-body-md font-body-md rounded-lg py-2 pl-3 pr-8 focus:border-primary focus:ring-0 cursor-pointer"
              value={filterAccount}
              onChange={(e) => setFilterAccount(e.target.value)}
            >
              <option value="all">所有账户</option>
              {ACCOUNTS.map((acct) => (
                <option key={acct.id} value={acct.id}>
                  {acct.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Summary card */}
        <div className="bg-primary text-on-primary rounded-xl p-4 flex flex-col justify-center relative overflow-hidden">
          <div className="absolute -right-10 -top-10 w-32 h-32 bg-primary-light opacity-10 rounded-full blur-2xl" />
          <span className="font-caption-sm text-caption-sm text-primary-light mb-1">
            当月结余
          </span>
          <span className="font-label-mono text-label-mono text-2xl">
            ¥ {formatMoney(net)}
          </span>
          <div className="flex justify-between mt-4 font-body-md text-body-md">
            <div className="flex flex-col">
              <span className="text-primary-light">收入</span>
              <span className="font-label-mono text-label-mono">+¥ {formatMoney(income)}</span>
            </div>
            <div className="flex flex-col text-right">
              <span className="text-primary-light">支出</span>
              <span className="font-label-mono text-label-mono">-¥ {formatMoney(expense)}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Transaction list grouped by date */}
      <div className="bg-bg-card rounded-xl border border-divider overflow-hidden">
        {filteredTxns.length === 0 ? (
          <p className="text-on-surface-variant font-body-md text-body-md text-center py-12">
            暂无交易记录
          </p>
        ) : (
          <div className="flex flex-col">
            {groupedTxns.map((group, idx) => (
              <div key={group.date} className={idx === 0 ? '' : 'mt-2'}>
                {/* Date header */}
                <div className="px-4 py-3 bg-surface-container-low border-b border-divider flex justify-between items-center">
                  <span className="font-headline-md text-headline-md text-text-primary text-sm">
                    {group.label}
                  </span>
                  <span className="font-caption-sm text-caption-sm text-on-surface-variant">
                    {group.net >= 0 ? '+' : '-'}¥ {formatMoney(group.net)}
                  </span>
                </div>

                {/* Tx items */}
                <div className="flex flex-col">
                  {group.txns.map((txn) => (
                    <TransactionRow
                      key={txn.id}
                      transaction={txn}
                      account={findAccount(txn.accountId)}
                      variant="comfortable"
                    />
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Load more */}
      <div className="mt-8 flex justify-center">
        <button
          type="button"
          className="px-6 py-2 border border-divider rounded-full font-body-md text-body-md text-on-surface-variant hover:bg-surface-container-low hover:text-text-primary transition-colors"
        >
          加载更多
        </button>
      </div>
    </div>
  )
}

// 007.跨端APP应用（移动端开发工程师）/src/pages/transactions/index.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useBookStore } from '@/stores/book'
import { useToastStore } from '@/stores/toast'
import { useLanguage } from '@/i18n/useLanguage'
import { listRecords, deleteRecord } from '@/api/records'
import { listAccounts } from '@/api/accounts'
import { listCategories } from '@/api/categories'
import TransactionRow from '@/components/TransactionRow.vue'
import type { Record } from '@/api/records'
import type { Account } from '@/api/accounts'
import type { Category } from '@/api/categories'
import { formatAmount } from '@/utils/finance'

const book = useBookStore()
const toast = useToastStore()
const { t } = useLanguage()

function currentMonth(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

function recentMonths(): string[] {
  const out: string[] = []
  const now = new Date()
  for (let i = 0; i < 6; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1)
    out.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`)
  }
  return out
}

function formatMonthLabel(m: string): string {
  const [y, mo] = m.split('-')
  return `${y}年 ${parseInt(mo, 10)}月`
}

const filterMonth = ref(currentMonth())
const filterCategory = ref('all')
const filterAccount = ref('all')

const records = ref<Record[]>([])
const accounts = ref<Account[]>([])
const cats = ref<Category[]>([])
const loading = ref(false)

const months = recentMonths()

const filteredRecords = computed(() => {
  return records.value.filter(r => {
    if (filterCategory.value !== 'all' && r.categoryId !== filterCategory.value) return false
    if (filterAccount.value !== 'all' && r.accountId !== filterAccount.value) return false
    return true
  }).sort((a, b) => (a.recordDate < b.recordDate ? 1 : -1))
})

const monthIncome = computed(() => filteredRecords.value.filter(r => r.type === 'income').reduce((s, r) => s + r.amount, 0))
const monthExpense = computed(() => filteredRecords.value.filter(r => r.type === 'expense').reduce((s, r) => s + r.amount, 0))
const monthNet = computed(() => monthIncome.value - monthExpense.value)

const grouped = computed(() => {
  const map = new Map<string, Record[]>()
  for (const r of filteredRecords.value) {
    const arr = map.get(r.recordDate) ?? []
    arr.push(r)
    map.set(r.recordDate, arr)
  }
  return Array.from(map.entries()).map(([date, recs]) => ({
    date,
    recs,
    net: recs.reduce((s, r) => s + (r.type === 'income' ? r.amount : -r.amount), 0),
  }))
})

const allCats = computed(() => cats.value)

function findAccount(id: string) { return accounts.value.find(a => a.id === id) }
function findCat(id: string | null) { return cats.value.find(c => c.id === id) }

async function load() {
  if (!book.current) return
  loading.value = true
  try {
    const [recs, accts, catsExp, catsInc] = await Promise.all([
      listRecords({ month: filterMonth.value, bookId: book.current.uuid }),
      listAccounts({ bookId: book.current.uuid }),
      listCategories('expense'),
      listCategories('income'),
    ])
    records.value = recs
    accounts.value = accts
    cats.value = [...catsExp, ...catsInc]
  } catch (e: any) {
    toast.show(t('transactions.loadErrorPrefix') + (e?.message ?? ''))
  } finally {
    loading.value = false
  }
}

async function remove(id: string) {
  uni.showModal({
    title: t('common.confirm'),
    content: t('transactions.deleteConfirm'),
    success: async (res) => {
      if (!res.confirm) return
      try {
        await deleteRecord(id)
        records.value = records.value.filter(r => r.id !== id)
        toast.show(t('common.delete') + ' OK')
      } catch (e: any) {
        toast.show(e?.message ?? t('common.error'))
      }
    },
  })
}

watch(filterMonth, load)
onMounted(load)
</script>

<template>
  <view class="page">
    <!-- Filter + Summary -->
    <view class="filter-row">
      <view class="filter-card">
        <text class="filter-title">{{ t('transactions.filterLabel') }}</text>
        <view class="filter-selects">
          <picker mode="selector" :range="months" :value="months.indexOf(filterMonth)" :range-text="months.map(formatMonthLabel)" @change="(e: any) => filterMonth = months[Number(e.detail.value)]">
            <view class="select-box">{{ formatMonthLabel(filterMonth) }} ▼</view>
          </picker>
          <picker mode="selector" :range="[{ id: 'all', name: t('transactions.allCategories') }, ...allCats]" range-key="name" :value="0" @change="(e: any) => filterCategory = [{ id: 'all', name: t('transactions.allCategories') }, ...allCats][Number(e.detail.value)]?.id ?? 'all'">
            <view class="select-box">{{ (([{ id: 'all', name: t('transactions.allCategories') }, ...allCats].find(c => c.id === filterCategory))?.name) || t('transactions.allCategories') }} ▼</view>
          </picker>
          <picker mode="selector" :range="[{ id: 'all', name: t('transactions.allAccounts') }, ...accounts]" range-key="name" :value="0" @change="(e: any) => filterAccount = [{ id: 'all', name: t('transactions.allAccounts') }, ...accounts][Number(e.detail.value)]?.id ?? 'all'">
            <view class="select-box">{{ (([{ id: 'all', name: t('transactions.allAccounts') }, ...accounts].find(a => a.id === filterAccount))?.name) || t('transactions.allAccounts') }} ▼</view>
          </picker>
        </view>
      </view>
      <view class="balance-card">
        <text class="balance-label">{{ t('transactions.monthBalance') }}</text>
        <text class="balance-amount" :class="monthNet >= 0 ? 'income' : 'expense'">
          {{ monthNet >= 0 ? '+' : '-' }}¥ {{ formatAmount(Math.abs(monthNet)) }}
        </text>
        <view class="balance-sub">
          <text class="income">{{ t('transactions.income') }}: +¥ {{ formatAmount(monthIncome) }}</text>
          <text class="expense">{{ t('transactions.expense') }}: -¥ {{ formatAmount(monthExpense) }}</text>
        </view>
      </view>
    </view>

    <!-- List -->
    <view class="list-card">
      <view v-if="loading" class="empty">{{ t('transactions.loading') }}</view>
      <view v-else-if="filteredRecords.length === 0" class="empty">{{ t('transactions.empty') }}</view>
      <view v-else>
        <view v-for="group in grouped" :key="group.date" class="day-group">
          <view class="day-header">
            <text class="day-label">{{ group.date }}</text>
            <text class="day-net" :class="group.net >= 0 ? 'income' : 'expense'">
              {{ group.net >= 0 ? '+' : '-' }}¥ {{ formatAmount(Math.abs(group.net)) }}
            </text>
          </view>
          <TransactionRow
            v-for="r in group.recs"
            :key="r.id"
            :record="r"
            :category="findCat(r.categoryId)"
            @tap="remove(r.id)"
          />
        </view>
      </view>
    </view>
  </view>
</template>

<style scoped>
.page { padding: 24rpx; display: flex; flex-direction: column; gap: 20rpx; }
.filter-row { display: flex; flex-direction: column; gap: 16rpx; }
.filter-card { background: var(--c-bg-card); border-radius: 16rpx; padding: 24rpx; }
.filter-title { font-size: 28rpx; font-weight: 600; margin-bottom: 16rpx; display: block; }
.filter-selects { display: flex; flex-wrap: wrap; gap: 12rpx; }
.select-box { border: 1px solid var(--c-divider); border-radius: 8rpx; padding: 12rpx 16rpx; font-size: 26rpx; background: var(--c-bg); }
.balance-card { background: var(--c-primary); border-radius: 16rpx; padding: 24rpx; color: #fff; }
.balance-label { font-size: 24rpx; opacity: 0.8; display: block; margin-bottom: 8rpx; }
.balance-amount { font-size: 40rpx; font-weight: 700; display: block; }
.balance-sub { display: flex; justify-content: space-between; margin-top: 12rpx; font-size: 24rpx; opacity: 0.9; }
.list-card { background: var(--c-bg-card); border-radius: 16rpx; overflow: hidden; }
.empty { text-align: center; padding: 80rpx; color: var(--c-text-variant); font-size: 28rpx; }
.day-group { border-bottom: 1px solid var(--c-divider); }
.day-group:last-child { border-bottom: none; }
.day-header { display: flex; justify-content: space-between; padding: 16rpx 24rpx; background: var(--c-surface); }
.day-label { font-size: 26rpx; font-weight: 600; color: var(--c-text-variant); }
.day-net { font-size: 26rpx; font-weight: 600; }
.income { color: #2E7DE6; }
.expense { color: var(--c-error); }
</style>
