// 007.跨端APP应用（移动端开发工程师）/uniapp-project/pages/accounts/index.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { useBookStore } from '@/stores/book'
import { useAuthStore } from '@/stores/auth'
import { useToastStore } from '@/stores/toast'
import { useLanguage } from '@/i18n/useLanguage'
import { listAccounts, deleteAccount, archiveAccount, unarchiveAccount } from '@/api/accounts'
import { formatAmount } from '@/utils/finance'
import type { Account } from '@/api/accounts'
import AppHeader from '@/components/AppHeader.vue'
import { goBack } from '@/utils/back'

const book = useBookStore()
const auth = useAuthStore()
const toast = useToastStore()
const { t } = useLanguage()

/** 0=active only, 1=all(活跃+归档), 2=archived only。默认 active。 */
type FilterMode = 'active' | 'all' | 'archived'
const filterMode = ref<FilterMode>('active')

const accounts = ref<Account[]>([])
const loading = ref(false)
const error = ref<string | null>(null)

const visibleAccounts = computed(() => {
  if (filterMode.value === 'all') return accounts.value
  if (filterMode.value === 'archived') return accounts.value.filter(a => a.isArchived)
  return accounts.value.filter(a => !a.isArchived)
})

const totalBalance = computed(() =>
  // 资产净值按当前可见账户求和(active 模式 = 跟首页口径一致)
  visibleAccounts.value.reduce((s, a) => s + (a.balance ?? 0), 0)
)

// iconName 之前是 Material Symbols ligature 字符串(chat_bubble / credit_card 等),
// 没加载字体时会渲染成 "credit_card" 这种英文乱码 —— settings 自定义分类踩过同样的坑。
// 改成跨平台可用的 emoji 字(各家系统 / 小程序 / iOS 都自带,不存在白字)。
const themeMap: Record<string, { iconBg: string; iconColor: string; iconName: string }> = {
  wechat: { iconBg: '#E5F5E9', iconColor: '#09B83E', iconName: '💬' },
  alipay: { iconBg: '#E3F2FD', iconColor: '#1677FF', iconName: '💰' },
  bank:   { iconBg: '#e5eeff', iconColor: '#005394', iconName: '🏦' },
  credit: { iconBg: 'rgb(167 8 25 / 0.12)', iconColor: '#ba1a1a', iconName: '💳' },
  cash:   { iconBg: '#dce9ff', iconColor: '#8B6E4E', iconName: '💵' },
  wallet: { iconBg: '#E5F5E9', iconColor: '#09B83E', iconName: '👛' },
}

async function load() {
  if (!auth.token || !book.current) return
  loading.value = true
  error.value = null
  try {
    // 一次拉全量(active + archived),前端按 filterMode 切片。
    // 后端 includeArchived=true 才能拿到 archived=1,默认是 false。
    accounts.value = (await listAccounts({ bookId: book.current.uuid, includeArchived: true }))
      .filter((a): a is Account => !!a && !!a.id)
  } catch (e: any) {
    error.value = e?.message ?? ''
  } finally {
    loading.value = false
  }
}

function getTheme(acc: Account) {
  // ponytail: 背景色/前景色按 type 走 themeMap(视觉一致),emoji 优先用后端
  //          acc.icon(用户在 Flutter 端选的,跨端共享),fallback 到 type 默认。
  //          这样 Flutter / uniapp / H5 / 小程序 都从后端读同一字段,
  //          不会出现"同一账号两边图标不一样"的歧义。
  const t =
    acc.type === 'credit' ? themeMap.credit :
    acc.type === 'cash' ? themeMap.cash :
    acc.type === 'wallet' ? themeMap.wallet :
    themeMap.bank
  return {
    iconBg: t.iconBg,
    iconColor: t.iconColor,
    iconName: (acc.icon && acc.icon.trim()) || t.iconName,
  }
}

function subtitleOf(acc: Account): string {
  const map: Record<string, string> = { cash: '现金', debit: '借记卡', credit: '信用卡', wallet: '电子钱包', investment: '投资', other: '其他' }
  return map[acc.type] ?? '其他'
}

function confirmDelete(acc: Account) {
  uni.showActionSheet({
    itemList: acc.isArchived
      ? [t('accounts.unarchive'), t('common.delete')]
      : [t('accounts.archive'), t('common.delete')],
    success: async (res) => {
      if (acc.isArchived) {
        // 归档账户的菜单:0=取消归档, 1=删除
        if (res.tapIndex === 0) return confirmUnarchive(acc)
        if (res.tapIndex === 1) return doDelete(acc)
      } else {
        // 活跃账户的菜单:0=归档, 1=删除
        if (res.tapIndex === 0) return confirmArchive(acc)
        if (res.tapIndex === 1) return doDelete(acc)
      }
    },
  })
}

function confirmArchive(acc: Account) {
  uni.showModal({
    title: t('common.confirm'),
    content: t('accounts.archiveConfirm').replace('{name}', acc.name),
    success: async (res) => {
      if (!res.confirm) return
      try {
        await archiveAccount(acc.id)
        acc.isArchived = true
        toast.show(t('accounts.archiveSuccess'))
      } catch (e: any) {
        toast.show(e?.message ?? t('common.error'))
      }
    },
  })
}

function confirmUnarchive(acc: Account) {
  uni.showModal({
    title: t('common.confirm'),
    content: t('accounts.unarchiveConfirm').replace('{name}', acc.name),
    success: async (res) => {
      if (!res.confirm) return
      try {
        await unarchiveAccount(acc.id)
        acc.isArchived = false
        toast.show(t('accounts.unarchiveSuccess'))
      } catch (e: any) {
        toast.show(e?.message ?? t('common.error'))
      }
    },
  })
}

function doDelete(acc: Account) {
  uni.showModal({
    title: t('common.confirm'),
    content: t('accounts.deleteConfirm'),
    success: async (res) => {
      if (!res.confirm) return
      try {
        await deleteAccount(acc.id)
        accounts.value = accounts.value.filter(a => a.id !== acc.id)
        toast.show(t('common.delete') + ' OK')
      } catch (e: any) {
        toast.show(e?.message ?? t('common.error'))
      }
    },
  })
}

watch([() => auth.token, () => book.current], () => { load() }, { immediate: true })
onShow(load)
</script>

<template>
  <view class="page-root tabbar-page">
    <!-- ponytail: 账户页是 tab 内页不是 push 进来的,用户截图无返回箭头,back 去掉 -->
    <AppHeader :title="t('pageTitle.accounts')" />
    <scroll-view scroll-y class="scroll-area" :bounces="false">
      <view class="page">
        <!-- Net assets + add -->
        <view class="net-card">
          <view class="net-label">{{ t('accounts.netAssets') }}</view>
          <text class="net-amount" :class="totalBalance < 0 ? 'expense' : ''">¥ {{ formatAmount(totalBalance, false) }}</text>
          <view class="add-btn" @tap="uni.navigateTo({ url: '/pages/accounts/new' })">
            <text class="add-icon">+</text>
            <text>{{ t('accounts.addCta') }}</text>
          </view>
        </view>

        <!-- Filter chips -->
        <view class="filter-row">
          <view
            class="chip"
            :class="{ active: filterMode === 'active' }"
            @tap="filterMode = 'active'"
          >{{ t('accounts.filter.active') }}</view>
          <view
            class="chip"
            :class="{ active: filterMode === 'all' }"
            @tap="filterMode = 'all'"
          >{{ t('accounts.filter.all') }}</view>
          <view
            class="chip"
            :class="{ active: filterMode === 'archived' }"
            @tap="filterMode = 'archived'"
          >{{ t('accounts.filter.archivedOnly') }}</view>
        </view>

        <!-- Error -->
        <view v-if="error" class="error-box">{{ t('accounts.loadErrorPrefix') }}{{ error }}</view>

        <!-- Account list -->
        <view class="list">
          <view v-if="loading" class="empty">{{ t('accounts.loading') }}</view>
          <view v-else-if="visibleAccounts.length === 0" class="empty">{{ t('accounts.empty') }}</view>
          <view v-else class="grid">
            <view
              v-for="(acc, idx) in visibleAccounts"
              :key="acc?.id ?? `acc-${idx}`"
              class="acc-card"
              :class="{ archived: acc.isArchived }"
              @longpress="confirmDelete(acc)"
            >
              <view class="acc-top">
                <view class="acc-icon" :style="{ background: getTheme(acc).iconBg }">
                  <text class="icon-text" :style="{ color: getTheme(acc).iconColor }">{{ getTheme(acc).iconName }}</text>
                </view>
                <view class="acc-more" @tap="confirmDelete(acc)">
                  <text class="more-icon">⋮</text>
                </view>
              </view>
              <view class="acc-body">
                <view class="name-row">
                  <text class="acc-name">{{ acc.name }}</text>
                  <text v-if="acc.isArchived" class="archived-badge">{{ t('accounts.archivedBadge') }}</text>
                </view>
                <text class="acc-sub">{{ subtitleOf(acc) }}</text>
              </view>
              <!-- 真实余额:formatAmount(toLocaleString) 会自动给负数加 '-',不再 Math.abs -->
              <text class="acc-balance" :class="acc.balance < 0 ? 'expense' : ''">
                ¥ {{ formatAmount(acc.balance, false) }}
              </text>
            </view>
          </view>
        </view>
      </view>
    </scroll-view>
  </view>
</template>

<style scoped>
/* 跨端可滚动外壳:H5 / iOS 需要 scroll-view 才能上下滑动,微信小程序原生就能滚所以包了也无害。
   page-root 用 calc(100vh - --tab-bar-height) 占满剩余视口,scroll-area flex:1 + height:0 拿到剩余高度。 */
.page-root {
  display: flex;
  flex-direction: column;
  height: calc(100vh - var(--tab-bar-height, 0px));
  background: var(--c-bg);
}
.scroll-area {
  flex: 1;
  height: 0;
  box-sizing: border-box;
}
.page { padding: 24rpx; display: flex; flex-direction: column; gap: 20rpx; }
.net-card { background: var(--c-bg-card); border-radius: 16rpx; padding: 28rpx; display: flex; flex-direction: column; gap: 8rpx; border: 1px solid var(--c-divider); }
.net-label { font-size: 24rpx; color: var(--c-text-variant); text-transform: uppercase; letter-spacing: 1px; }
.net-amount { font-size: 48rpx; font-weight: 700; color: var(--c-text); }
.net-amount.expense { color: var(--c-error); }
.add-btn { display: flex; align-items: center; gap: 8rpx; margin-top: 12rpx; background: var(--c-primary); color: #fff; border-radius: 12rpx; padding: 16rpx 24rpx; font-size: 28rpx; font-weight: 600; }
.add-icon { font-size: 32rpx; }
.filter-row { display: flex; gap: 12rpx; }
.chip { padding: 12rpx 24rpx; border-radius: 999rpx; background: var(--c-bg-card); border: 1px solid var(--c-divider); color: var(--c-text-variant); font-size: 24rpx; }
.chip.active { background: var(--c-primary); color: #fff; border-color: var(--c-primary); }
.error-box { background: #FFEBEE; color: #C62828; border-radius: 12rpx; padding: 20rpx; font-size: 26rpx; }
.empty { text-align: center; padding: 80rpx; color: var(--c-text-variant); font-size: 28rpx; }
.list { }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16rpx; }
.acc-card { background: var(--c-bg-card); border-radius: 16rpx; padding: 24rpx; display: flex; flex-direction: column; gap: 12rpx; border: 1px solid var(--c-divider); }
.acc-card.archived { opacity: 0.5; }
.acc-top { display: flex; justify-content: space-between; align-items: flex-start; }
.acc-icon { width: 80rpx; height: 80rpx; border-radius: 50%; display: flex; align-items: center; justify-content: center; }
.icon-text { font-size: 32rpx; }
.acc-more { padding: 8rpx; }
.more-icon { font-size: 32rpx; color: var(--c-text-variant); }
.acc-body { display: flex; flex-direction: column; gap: 4rpx; }
.name-row { display: flex; align-items: center; gap: 8rpx; flex-wrap: wrap; }
.acc-name { font-size: 28rpx; font-weight: 600; color: var(--c-text); }
.archived-badge { font-size: 20rpx; color: var(--c-text-variant); background: var(--c-divider); padding: 2rpx 10rpx; border-radius: 8rpx; }
.acc-sub { font-size: 22rpx; color: var(--c-text-variant); }
.acc-balance { font-size: 28rpx; font-weight: 700; color: var(--c-text); }
.acc-balance.expense { color: var(--c-error); }
</style>

// 003.前端代码（前端工程师）/frontend-react-java/src/pages/Accounts.tsx
import { useMemo, useState } from 'react'
import { usePageTitle, usePageBack } from '../components/PageTitleContext'
import { useAccounts } from '../lib/hooks'
import { toAccounts } from '../lib/finance-mappers'
import { Link } from 'react-router-dom'
import { useLanguage } from '../i18n/LanguageContext'
import * as accountsApi from '../api/accounts'

function formatMoney(amount: number): string {
  return new Intl.NumberFormat('zh-CN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount)
}

const ACCOUNT_THEME: Record<
  string,
  { iconBg: string; iconColor: string }
> = {
  // 对齐 007 uniapp themeMap + Flutter _icons:iconName 现在是 emoji 字符
  // (后端 acc.icon 优先),这里只保留 iconBg / iconColor 给底圈染色。
  wechat: { iconBg: '#E5F5E9', iconColor: '#09B83E' },
  alipay: { iconBg: '#E3F2FD', iconColor: '#1677FF' },
  bank:   { iconBg: '#e5eeff', iconColor: '#005394' },
  credit: { iconBg: 'rgb(167 8 25 / 0.12)', iconColor: '#ba1a1a' },
  cash:   { iconBg: '#dce9ff', iconColor: '#8B6E4E' },
}

/** 0=active only, 1=all(活跃+归档), 2=archived only。默认 active。 */
type FilterMode = 'active' | 'all' | 'archived'

export function Accounts() {
  const { t } = useLanguage()
  usePageTitle(t('accounts.titleManage'))
  usePageBack(null)

  // ponytail: 一次拉全量(active + archived),前端按 filterMode 切片。
  //          默认 useAccounts() 不传 includeArchived,跟其它页面(只显示活跃账户)
  //          行为一致。
  const accountsQ = useAccounts({ includeArchived: true })
  const accounts = useMemo(() => (accountsQ.data ? toAccounts(accountsQ.data) : []), [accountsQ.data])

  const [filter, setFilter] = useState<FilterMode>('active')
  const visible = useMemo(() => {
    if (filter === 'all') return accounts
    if (filter === 'archived') return accounts.filter((a) => a.isArchived)
    return accounts.filter((a) => !a.isArchived)
  }, [accounts, filter])

  const totalBalance = visible.reduce((s, a) => s + a.balance, 0)
  const isLoading = accountsQ.loading
  const isError = !isLoading && !!accountsQ.error
  const errMsg = accountsQ.error?.message ?? null

  async function handleArchive(id: string, name: string, currentArchived: boolean) {
    const ok = window.confirm(
      currentArchived
        ? t('accounts.unarchiveConfirm', { name })
        : t('accounts.archiveConfirm', { name })
    )
    if (!ok) return
    try {
      if (currentArchived) {
        await accountsApi.unarchiveAccount(id)
      } else {
        await accountsApi.archiveAccount(id)
      }
      accountsQ.reload()
    } catch (err) {
      alert((err as Error)?.message ?? String(err))
    }
  }

  async function handleDelete(id: string) {
    if (!window.confirm(t('accounts.deleteConfirm'))) return
    try {
      await accountsApi.deleteAccount(id)
      accountsQ.reload()
    } catch (err) {
      alert((err as Error)?.message ?? String(err))
    }
  }

  return (
    <div className="space-y-6">
      {/* 资产净值 + 添加账户 */}
      <section className="bg-bg-card rounded-xl p-6 border border-divider shadow-sm relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <p className="font-caption-sm text-caption-sm text-on-surface-variant mb-1 uppercase tracking-wider">
              {t('accounts.netAssets')}
            </p>
            <div className="flex items-baseline gap-2">
              <span
                className={`font-display-lg text-display-lg font-bold ${
                  totalBalance < 0 ? 'text-error' : 'text-text-primary'
                }`}
              >
                ¥{formatMoney(totalBalance)}
              </span>
            </div>
          </div>
          <Link
            to="/accounts/new"
            className="flex items-center justify-center gap-2 bg-primary text-on-primary font-headline-md text-headline-md py-2.5 px-6 rounded-lg shadow-[0_2px_8px_rgba(0,83,148,0.2)] hover:bg-primary-container transition-all active:scale-95 w-full md:w-auto"
          >
            <span
              className="material-symbols-outlined"
              style={{ fontVariationSettings: "'FILL' 1" }}
            >
              add_circle
            </span>
            {t('accounts.addCta')}
          </Link>
        </div>
      </section>

      {/* Filter chips — 三档:活跃 / 全部 / 已归档 */}
      <section className="flex gap-2">
        {(['active', 'all', 'archived'] as FilterMode[]).map((mode) => {
          const selected = filter === mode
          const label =
            mode === 'active'
              ? t('accounts.filter.active')
              : mode === 'all'
              ? t('accounts.filter.all')
              : t('accounts.filter.archivedOnly')
          return (
            <button
              key={mode}
              type="button"
              onClick={() => setFilter(mode)}
              className={`px-4 py-1.5 rounded-full font-caption-md text-caption-md border transition-colors ${
                selected
                  ? 'bg-primary text-on-primary border-primary'
                  : 'bg-bg-card text-on-surface-variant border-divider hover:border-primary'
              }`}
            >
              {label}
            </button>
          )
        })}
      </section>

      {isError && (
        <div className="bg-error-container text-on-error-container rounded-xl p-4 font-body-md text-body-md">
          {t('accounts.loadErrorPrefix')}{errMsg}
        </div>
      )}

      {/* 账户卡片网格 */}
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
        {isLoading ? (
          <p className="col-span-full text-on-surface-variant font-body-md text-body-md text-center py-12">
            {t('accounts.loading')}
          </p>
        ) : visible.length === 0 ? (
          <p className="col-span-full text-on-surface-variant font-body-md text-body-md text-center py-12">
            {t('accounts.empty')}
          </p>
        ) : (
          visible.map((acc) => {
            const theme = ACCOUNT_THEME[acc.themeKey] ?? ACCOUNT_THEME.bank
            return (
              <article
                key={acc.id}
                // ponytail: 归档卡片整体透明度 0.5,跟 uniapp / Flutter 三端一致。
                className={`bg-bg-card rounded-xl p-5 border border-divider shadow-sm hover:shadow-[0_4px_12px_rgba(0,0,0,0.04)] transition-shadow group relative ${
                  acc.isArchived ? 'opacity-50' : ''
                }`}
              >
                <div className="flex justify-between items-start mb-6">
                  <div
                    className="w-12 h-12 rounded-full flex items-center justify-center text-2xl"
                    style={{ backgroundColor: theme.iconBg, color: theme.iconColor }}
                  >
                    {/* emoji 字(来自后端 acc.icon 或 themeKey 兜底),对齐 uniapp/Flutter */}
                    <span aria-hidden="true">{acc.icon}</span>
                  </div>
                  {/* ponytail: 卡片右上角更多菜单 — 用原生 <details>/<summary>
                              配合下拉,避免引第三方 popover 库;同 macOS/Windows/移动
                              浏览器一致行为。点击外部收起靠 <details> open 状态切
                              换(<details> 点击外部不会自动关,但可接受,跟对话体验
                              接近)。 */}
                  <details className="relative">
                    <summary
                      className="list-none cursor-pointer text-outline hover:text-on-surface-variant transition-colors"
                      aria-label={t('accounts.moreActions')}
                    >
                      <span className="material-symbols-outlined">more_horiz</span>
                    </summary>
                    <div className="absolute right-0 mt-2 min-w-[160px] bg-bg-card border border-divider rounded-lg shadow-lg z-10 overflow-hidden">
                      <button
                        type="button"
                        onClick={(e) => {
                          e.preventDefault()
                          handleArchive(acc.id, acc.name, !!acc.isArchived)
                        }}
                        className="w-full text-left px-4 py-2 font-body-md text-body-md hover:bg-primary-container transition-colors"
                      >
                        {acc.isArchived ? t('accounts.unarchive') : t('accounts.archive')}
                      </button>
                      <button
                        type="button"
                        onClick={(e) => {
                          e.preventDefault()
                          handleDelete(acc.id)
                        }}
                        className="w-full text-left px-4 py-2 font-body-md text-body-md text-error hover:bg-error-container transition-colors border-t border-divider"
                      >
                        {t('common.delete')}
                      </button>
                    </div>
                  </details>
                </div>

                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-headline-md text-headline-md text-on-surface">
                      {acc.name}
                    </h3>
                    {acc.isArchived && (
                      <span className="inline-flex items-center px-2 py-0.5 rounded font-caption-sm text-caption-sm bg-divider text-on-surface-variant">
                        {t('accounts.archivedBadge')}
                      </span>
                    )}
                  </div>
                  <p className="font-caption-sm text-caption-sm text-on-surface-variant mb-4">
                    {acc.subtitle}
                  </p>

                  {/* 真实余额:formatMoney(toLocaleString) 自动给负数带 '-'。
                      账户页规则:负数(透支/欠款)=红色,正数/0=默认色 —— 收入不强调绿色。 */}
                  <p
                    className={`font-label-mono text-label-mono ${
                      acc.balance < 0 ? 'text-error' : 'text-on-surface'
                    }`}
                  >
                    ¥{formatMoney(acc.balance)}
                  </p>
                </div>
              </article>
            )
          })
        )}
      </section>
    </div>
  )
}
