// 007.跨端APP应用（移动端开发工程师）/uniapp-project/pages/books/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useBookStore } from '@/stores/book'
import { useToastStore } from '@/stores/toast'
import { useLanguage } from '@/i18n/useLanguage'
import { listBooks, createBook, updateBook, deleteBook } from '@/api/books'
import type { Book, BookType } from '@/api/books'

const bookStore = useBookStore()
const toast = useToastStore()
const { t } = useLanguage()

const books = ref<Book[]>([])
const loading = ref(false)
const error = ref<string | null>(null)
const busy = ref(false)

const showCreate = ref(false)
const newName = ref('')
const newType = ref<BookType>('personal')
const newDesc = ref('')

const editing = ref<Book | null>(null)
const editDesc = ref('')

const typeOptions: { value: BookType; label: string }[] = [
  { value: 'personal', label: '个人' },
  { value: 'shared', label: '共享' },
  { value: 'business', label: '生意' },
]

async function load() {
  loading.value = true
  error.value = null
  try {
    books.value = await listBooks()
  } catch (e: any) {
    error.value = e?.message ?? ''
  } finally {
    loading.value = false
  }
}

async function handleCreate() {
  if (!newName.value.trim()) return
  busy.value = true
  try {
    await createBook({ name: newName.value.trim(), type: newType.value, description: newDesc.value.trim() || undefined })
    showCreate.value = false
    newName.value = ''
    newDesc.value = ''
    newType.value = 'personal'
    toast.show(t('books.create.success'))
    await load()
  } catch (e: any) {
    toast.show(t('books.create.failPrefix') + (e?.message ?? ''))
  } finally {
    busy.value = false
  }
}

async function handleSwitch(uuid: string) {
  try {
    await bookStore.setCurrent(uuid)
    toast.show(t('books.action.switch') + ' OK')
  } catch (e: any) {
    toast.show(t('books.switch.failPrefix') + (e?.message ?? ''))
  }
}

function openEdit(b: Book) {
  editing.value = b
  editDesc.value = b.description ?? ''
}

async function handleSaveEdit() {
  if (!editing.value) return
  busy.value = true
  try {
    await updateBook(editing.value.uuid, { description: editDesc.value.trim() || null })
    editing.value = null
    toast.show(t('books.edit.success'))
    await load()
  } catch (e: any) {
    toast.show(t('books.edit.failPrefix') + (e?.message ?? ''))
  } finally {
    busy.value = false
  }
}

async function handleDelete(b: Book) {
  uni.showModal({
    title: t('common.confirm'),
    content: t('books.delete.confirm', { name: b.name }),
    success: async (res) => {
      if (!res.confirm) return
      busy.value = true
      try {
        await deleteBook(b.uuid)
        toast.show(t('books.delete.success'))
        await load()
      } catch (e: any) {
        toast.show(t('books.delete.failPrefix') + (e?.message ?? ''))
      } finally {
        busy.value = false
      }
    },
  })
}

function typeIcon(t: BookType): string {
  return t === 'shared' ? 'group' : t === 'business' ? 'business_center' : 'person'
}

onMounted(load)
</script>

<template>
  <view class="page">
    <!-- Header -->
    <view class="header-row">
      <text class="page-title">{{ t('books.heading') }}</text>
      <view class="add-btn" @tap="showCreate = !showCreate">
        <text>+ {{ t('books.create.toggle') }}</text>
      </view>
    </view>

    <!-- Create form -->
    <view v-if="showCreate" class="card">
      <text class="card-title">{{ t('books.create.title') }}</text>
      <view class="form-grid">
        <view class="field">
          <text class="field-label">{{ t('books.create.name') }}</text>
          <input v-model="newName" class="field-input" :placeholder="t('books.create.namePlaceholder')" maxlength="50" />
        </view>
        <view class="field">
          <text class="field-label">{{ t('books.create.type') }}</text>
          <picker mode="selector" :range="typeOptions" range-key="label" :value="0" @change="(e: any) => newType = typeOptions[e.detail.value].value">
            <view class="field-picker">
              <text>{{ typeOptions.find(o => o.value === newType)?.label }}</text>
              <text class="arrow">▼</text>
            </view>
          </picker>
        </view>
        <view class="field full">
          <text class="field-label">{{ t('books.create.description') }}</text>
          <input v-model="newDesc" class="field-input" :placeholder="t('books.create.descPlaceholder')" maxlength="200" />
        </view>
      </view>
      <view class="btn-row">
        <view class="btn-cancel" @tap="showCreate = false" :class="{ disabled: busy }">{{ t('common.cancel') }}</view>
        <view class="btn-confirm" @tap="handleCreate" :class="{ disabled: busy || !newName.trim() }">
          {{ busy ? t('common.loading') : t('common.save') }}
        </view>
      </view>
    </view>

    <!-- Error -->
    <view v-if="error" class="error-box">{{ t('common.error') }}: {{ error }}</view>

    <!-- Loading -->
    <view v-if="loading && !books.length" class="empty">{{ t('common.loading') }}</view>

    <!-- Empty -->
    <view v-if="!loading && books.length === 0" class="empty">{{ t('books.empty') }}</view>

    <!-- Books grid -->
    <view v-if="books.length" class="grid">
      <view v-for="b in books" :key="b.uuid" class="book-card" :class="{ current: bookStore.currentId === b.uuid }">
        <view class="book-top">
          <view class="book-info">
            <text class="book-name">{{ b.name }}</text>
            <text class="book-desc">{{ b.description || t('books.noDesc') }}</text>
          </view>
          <view v-if="b.isDefault" class="badge">{{ t('books.badge.default') }}</view>
        </view>
        <view class="book-meta">
          <text class="meta-icon">{{ typeIcon(b.type) }}</text>
          <text>{{ t(`books.type.${b.type}`) }}</text>
          <text class="sep">·</text>
          <text>{{ t(`books.role.${b.role}`) }}</text>
        </view>
        <view class="book-actions">
          <view v-if="bookStore.currentId !== b.uuid" class="action-btn" @tap="handleSwitch(b.uuid)">
            {{ t('books.action.switch') }}
          </view>
          <view v-else class="action-btn current-btn">{{ t('books.badge.current') }}</view>
          <view class="action-btn" @tap="uni.navigateTo({ url: `/pages/books/members?id=${b.uuid}` })">
            {{ t('books.action.members') }}
          </view>
          <view v-if="b.role === 'owner'" class="action-btn" @tap="openEdit(b)">{{ t('common.edit') }}</view>
          <view v-if="b.role === 'owner' && !b.isDefault" class="action-btn danger" @tap="handleDelete(b)">
            {{ t('common.delete') }}
          </view>
        </view>
      </view>
    </view>

    <!-- Edit modal -->
    <view v-if="editing" class="modal-mask" @tap.self="editing = null">
      <view class="modal-card">
        <text class="modal-title">{{ t('books.edit.title', { name: editing.name }) }}</text>
        <view class="field">
          <text class="field-label">{{ t('books.create.description') }}</text>
          <input v-model="editDesc" class="field-input" maxlength="200" />
        </view>
        <view class="btn-row">
          <view class="btn-cancel" @tap="editing = null">{{ t('common.cancel') }}</view>
          <view class="btn-confirm" @tap="handleSaveEdit" :class="{ disabled: busy }">{{ t('common.save') }}</view>
        </view>
      </view>
    </view>
  </view>
</template>

<style scoped>
.page { padding: 24rpx; display: flex; flex-direction: column; gap: 20rpx; }
.header-row { display: flex; justify-content: space-between; align-items: center; }
.page-title { font-size: 36rpx; font-weight: 700; color: var(--c-text); }
.add-btn { display: flex; align-items: center; gap: 8rpx; background: var(--c-primary); color: #fff; border-radius: 12rpx; padding: 12rpx 20rpx; font-size: 26rpx; font-weight: 600; }
.card { background: var(--c-bg-card); border-radius: 16rpx; padding: 24rpx; display: flex; flex-direction: column; gap: 20rpx; border: 1px solid var(--c-divider); }
.card-title { font-size: 28rpx; font-weight: 600; color: var(--c-text); }
.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16rpx; }
.field { display: flex; flex-direction: column; gap: 6rpx; }
.field.full { grid-column: 1 / -1; }
.field-label { font-size: 24rpx; color: var(--c-text-variant); }
.field-input { border: 1rpx solid var(--c-divider); border-radius: 8rpx; padding: 12rpx 16rpx; font-size: 26rpx; color: var(--c-text); background: var(--c-surface); }
.field-picker { border: 1rpx solid var(--c-divider); border-radius: 8rpx; padding: 12rpx 16rpx; display: flex; justify-content: space-between; font-size: 26rpx; color: var(--c-text); }
.arrow { color: var(--c-text-variant); font-size: 20rpx; }
.btn-row { display: flex; gap: 12rpx; }
.btn-cancel { flex: 1; text-align: center; padding: 16rpx; border: 1rpx solid var(--c-divider); border-radius: 8rpx; font-size: 26rpx; color: var(--c-text); }
.btn-confirm { flex: 1; text-align: center; padding: 16rpx; background: var(--c-primary); color: #fff; border-radius: 8rpx; font-size: 26rpx; }
.btn-cancel.disabled, .btn-confirm.disabled { opacity: 0.5; }
.error-box { background: #FFEBEE; color: #C62828; border-radius: 12rpx; padding: 20rpx; font-size: 26rpx; }
.empty { text-align: center; padding: 80rpx; color: var(--c-text-variant); font-size: 28rpx; }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16rpx; }
.book-card { background: var(--c-bg-card); border-radius: 16rpx; padding: 20rpx; border: 2rpx solid transparent; display: flex; flex-direction: column; gap: 12rpx; }
.book-card.current { border-color: var(--c-primary); }
.book-top { display: flex; justify-content: space-between; align-items: flex-start; gap: 8rpx; }
.book-info { display: flex; flex-direction: column; gap: 4rpx; flex: 1; }
.book-name { font-size: 28rpx; font-weight: 600; color: var(--c-text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.book-desc { font-size: 22rpx; color: var(--c-text-variant); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.badge { background: var(--c-primary-light); color: var(--c-primary); border-radius: 8rpx; padding: 4rpx 10rpx; font-size: 20rpx; font-weight: 600; flex-shrink: 0; }
.book-meta { display: flex; align-items: center; gap: 6rpx; font-size: 22rpx; color: var(--c-text-variant); }
.meta-icon { font-size: 20rpx; }
.sep { color: var(--c-divider); }
.book-actions { display: flex; flex-wrap: wrap; gap: 8rpx; }
.action-btn { padding: 8rpx 16rpx; border: 1rpx solid var(--c-primary); color: var(--c-primary); border-radius: 8rpx; font-size: 22rpx; }
.action-btn.current-btn { background: var(--c-primary-light); font-weight: 600; }
.action-btn.danger { border-color: var(--c-error); color: var(--c-error); }
.modal-mask { position: fixed; inset: 0; background: rgba(0,0,0,0.4); display: flex; align-items: center; justify-content: center; z-index: 100; padding: 32rpx; }
.modal-card { background: var(--c-bg-card); border-radius: 16rpx; padding: 32rpx; width: 100%; max-width: 600rpx; display: flex; flex-direction: column; gap: 20rpx; }
.modal-title { font-size: 32rpx; font-weight: 600; color: var(--c-text); }
</style>

// 003.前端代码（前端工程师）/frontend-react-java/src/pages/Books.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { usePageTitle } from '../components/PageTitleContext'
import { useLanguage } from '../i18n/LanguageContext'
import { useBooks, BOOK_CHANGED_EVENT } from '../lib/hooks'
import { useCurrentBook } from '../lib/book-context'
import * as booksApi from '../api/books'
import type { Book, BookType } from '../api/books'
import { ApiError } from '../lib/api'
import { useToast } from '../components/Toast'

const TYPE_OPTIONS: { value: BookType; labelKey: string }[] = [
  { value: 'personal', labelKey: 'books.type.personal' },
  { value: 'shared', labelKey: 'books.type.shared' },
  { value: 'business', labelKey: 'books.type.business' },
]

const ROLE_LABEL_KEY: Record<Book['role'], string> = {
  owner: 'books.role.owner',
  admin: 'books.role.admin',
  editor: 'books.role.editor',
  viewer: 'books.role.viewer',
}

export function Books() {
  const { t } = useLanguage()
  const toast = useToast()
  const navigate = useNavigate()
  const { data: books, loading, error, reload } = useBooks()
  const { currentBook, setCurrentBook } = useCurrentBook()

  const [showCreate, setShowCreate] = useState(false)
  const [newName, setNewName] = useState('')
  const [newType, setNewType] = useState<BookType>('personal')
  const [newDesc, setNewDesc] = useState('')
  const [busy, setBusy] = useState(false)

  const [editing, setEditing] = useState<Book | null>(null)
  const [editDesc, setEditDesc] = useState('')

  usePageTitle(t('pageTitle.books'))

  async function handleCreate(): Promise<void> {
    if (!newName.trim()) return
    setBusy(true)
    try {
      await booksApi.createBook({ name: newName.trim(), type: newType, description: newDesc.trim() || undefined })
      setShowCreate(false)
      setNewName('')
      setNewDesc('')
      setNewType('personal')
      window.dispatchEvent(new Event(BOOK_CHANGED_EVENT))
      toast.show(t('books.create.success'))
      await reload()
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : String(err)
      toast.show(`${t('books.create.failPrefix')}${msg}`)
    } finally {
      setBusy(false)
    }
  }

  async function handleSwitch(uuid: string): Promise<void> {
    try {
      await setCurrentBook(uuid)
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : String(err)
      toast.show(`${t('books.switch.failPrefix')}${msg}`)
    }
  }

  function openEdit(b: Book): void {
    setEditing(b)
    setEditDesc(b.description ?? '')
  }

  async function handleSaveEdit(): Promise<void> {
    if (!editing) return
    setBusy(true)
    try {
      await booksApi.updateBook(editing.uuid, { description: editDesc.trim() || null })
      setEditing(null)
      window.dispatchEvent(new Event(BOOK_CHANGED_EVENT))
      toast.show(t('books.edit.success'))
      await reload()
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : String(err)
      toast.show(`${t('books.edit.failPrefix')}${msg}`)
    } finally {
      setBusy(false)
    }
  }

  async function handleDelete(b: Book): Promise<void> {
    if (!window.confirm(t('books.delete.confirm', { name: b.name }))) return
    setBusy(true)
    try {
      await booksApi.deleteBook(b.uuid)
      window.dispatchEvent(new Event(BOOK_CHANGED_EVENT))
      toast.show(t('books.delete.success'))
      await reload()
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : String(err)
      toast.show(`${t('books.delete.failPrefix')}${msg}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="font-headline-md text-headline-md text-on-surface">
          {t('books.heading')}
        </h2>
        <button
          type="button"
          onClick={() => setShowCreate((v) => !v)}
          className="inline-flex items-center gap-2 px-4 py-2 bg-primary text-on-primary rounded-lg hover:bg-primary-container transition-colors font-body-md text-body-md"
        >
          <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>add</span>
          {t('books.create.toggle')}
        </button>
      </div>

      {showCreate && (
        <div className="bento-item bg-bg-card p-6">
          <h3 className="font-headline-md text-headline-md text-text-primary mb-4">
            {t('books.create.title')}
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <label className="flex flex-col gap-1">
              <span className="font-body-md text-body-md text-on-surface-variant">
                {t('books.create.name')}
              </span>
              <input
                value={newName}
                onChange={(e) => setNewName(e.target.value)}
                maxLength={50}
                className="border border-outline rounded-lg px-3 py-2 font-body-md text-body-md bg-surface-container-lowest focus:border-primary focus:ring-1 focus:ring-primary"
                placeholder={t('books.create.namePlaceholder')}
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="font-body-md text-body-md text-on-surface-variant">
                {t('books.create.type')}
              </span>
              <select
                value={newType}
                onChange={(e) => setNewType(e.target.value as BookType)}
                className="border border-outline rounded-lg px-3 py-2 font-body-md text-body-md bg-surface-container-lowest focus:border-primary"
              >
                {TYPE_OPTIONS.map((opt) => (
                  <option key={opt.value} value={opt.value}>{t(opt.labelKey)}</option>
                ))}
              </select>
            </label>
            <label className="flex flex-col gap-1 md:col-span-3">
              <span className="font-body-md text-body-md text-on-surface-variant">
                {t('books.create.description')}
              </span>
              <input
                value={newDesc}
                onChange={(e) => setNewDesc(e.target.value)}
                maxLength={200}
                className="border border-outline rounded-lg px-3 py-2 font-body-md text-body-md bg-surface-container-lowest focus:border-primary"
                placeholder={t('books.create.descPlaceholder')}
              />
            </label>
          </div>
          <div className="flex justify-end gap-2 mt-4">
            <button
              type="button"
              onClick={() => setShowCreate(false)}
              disabled={busy}
              className="px-4 py-2 border border-outline rounded-lg hover:bg-surface-container-low font-body-md text-body-md"
            >
              {t('common.cancel')}
            </button>
            <button
              type="button"
              onClick={handleCreate}
              disabled={busy || !newName.trim()}
              className="px-4 py-2 bg-primary text-on-primary rounded-lg hover:bg-primary-container font-body-md text-body-md disabled:opacity-50"
            >
              {busy ? t('common.loading') : t('common.save')}
            </button>
          </div>
        </div>
      )}

      {error && (
        <div className="bento-item bg-error-container p-4 text-error font-body-md text-body-md">
          {t('common.error')}: {error.message}
        </div>
      )}

      {loading && !books && (
        <p className="font-body-md text-body-md text-on-surface-variant">{t('common.loading')}</p>
      )}

      {books && books.length === 0 && (
        <p className="font-body-md text-body-md text-on-surface-variant">{t('books.empty')}</p>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {books?.map((b) => {
          const isCurrent = currentBook?.uuid === b.uuid
          const isOwner = b.role === 'owner'
          return (
            <div
              key={b.uuid}
              className={`bento-item bg-bg-card p-6 border ${
                isCurrent ? 'border-primary ring-2 ring-primary-light' : 'border-divider'
              }`}
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex-1 min-w-0">
                  <h3 className="font-headline-md text-headline-md text-text-primary truncate">
                    {b.name}
                  </h3>
                  <p className="font-body-md text-body-md text-on-surface-variant truncate">
                    {b.description || t('books.noDesc')}
                  </p>
                </div>
                {b.isDefault && (
                  <span className="ml-2 px-2 py-0.5 rounded-full bg-primary-light text-primary text-xs font-semibold flex-shrink-0">
                    {t('books.badge.default')}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2 mb-4 text-sm text-on-surface-variant">
                <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>
                  {b.type === 'shared' ? 'group' : b.type === 'business' ? 'business_center' : 'person'}
                </span>
                <span>{t(`books.type.${b.type}`)}</span>
                <span className="text-divider">·</span>
                <span>{t(ROLE_LABEL_KEY[b.role])}</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {!isCurrent && (
                  <button
                    type="button"
                    onClick={() => handleSwitch(b.uuid)}
                    className="px-3 py-1.5 text-sm border border-primary text-primary rounded-lg hover:bg-primary-light transition-colors"
                  >
                    {t('books.action.switch')}
                  </button>
                )}
                {isCurrent && (
                  <span className="px-3 py-1.5 text-sm bg-primary-light text-primary rounded-lg font-semibold">
                    {t('books.badge.current')}
                  </span>
                )}
                <button
                  type="button"
                  onClick={() => navigate(`/books/${b.uuid}/members`)}
                  className="px-3 py-1.5 text-sm border border-outline rounded-lg hover:bg-surface-container-low transition-colors"
                >
                  {t('books.action.members')}
                </button>
                {isOwner && (
                  <>
                    <button
                      type="button"
                      onClick={() => openEdit(b)}
                      className="px-3 py-1.5 text-sm border border-outline rounded-lg hover:bg-surface-container-low transition-colors"
                    >
                      {t('common.edit')}
                    </button>
                    {!b.isDefault && (
                      <button
                        type="button"
                        onClick={() => handleDelete(b)}
                        disabled={busy}
                        className="px-3 py-1.5 text-sm border border-error text-error rounded-lg hover:bg-error hover:text-white transition-colors disabled:opacity-50"
                      >
                        {t('common.delete')}
                      </button>
                    )}
                  </>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {editing && (
        <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4">
          <div className="bg-bg-card rounded-xl p-6 w-full max-w-md">
            <h3 className="font-headline-md text-headline-md text-text-primary mb-4">
              {t('books.edit.title', { name: editing.name })}
            </h3>
            <label className="flex flex-col gap-1 mb-4">
              <span className="font-body-md text-body-md text-on-surface-variant">
                {t('books.create.description')}
              </span>
              <input
                value={editDesc}
                onChange={(e) => setEditDesc(e.target.value)}
                className="border border-outline rounded-lg px-3 py-2 font-body-md text-body-md bg-surface-container-lowest focus:border-primary"
                maxLength={200}
              />
            </label>
            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setEditing(null)}
                className="px-4 py-2 border border-outline rounded-lg font-body-md text-body-md"
              >
                {t('common.cancel')}
              </button>
              <button
                type="button"
                onClick={handleSaveEdit}
                disabled={busy}
                className="px-4 py-2 bg-primary text-on-primary rounded-lg font-body-md text-body-md disabled:opacity-50"
              >
                {t('common.save')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
